version: "3.5"

services:

  bd:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=itutor
      - MYSQL_ROOT_PASSWORD=12345Abcde
      - MYSQL_USER=itutor
      - MYSQL_PASSWORD=12345Abcde
    volumes:
      - mariadb:/var/lib/mysql
      - ./config/sql:/docker-entrypoint-initdb.d:ro
    expose:
      - 3306

  web:
    build:
      context: ./config
      dockerfile: Dockerfile.web
    depends_on:
      - bd
    volumes:
      - ./app:/var/www
      - ./app/web:/var/www/html
      - ./app/lib/vendor/symfony/data/web/sf:/var/www/html/sf
      - symfony_cache:/var/www/cache
      - symfony_log:/var/www/log
      - apache_log:/var/log/apache2
      - goaccess:/var/www/html/goaccess:ro
    expose:
      - 80
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - bd
    environment:
      - PMA_HOST=bd
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=12345Abcde
    ports:
      - 8080:80

  goaccess:
    image: allinurl/goaccess:latest
    depends_on:
      - web
    volumes:
      - ./config/goaccess:/srv/data
      - apache_log:/srv/logs:ro
      - goaccess:/srv/report
    ports:
      - 7890:7890
    restart: always

volumes:
  mariadb:
  apache_log:
  goaccess:
  symfony_cache:
  symfony_log:
