services:

  bd:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-itutor}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-12345Abcde}
      - MYSQL_USER=${MYSQL_USER:-itutor}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-12345Abcde}
    volumes:
      - mariadb:/var/lib/mysql
      - ./config/sql:/docker-entrypoint-initdb.d:ro
    expose:
      - 3306
    restart: unless-stopped

  web:
    platform: linux/amd64
    build:
      context: ./config
      dockerfile: Dockerfile.web
    depends_on:
      - bd
    volumes:
      - ./app:/var/www
      - ./app/web:/var/www/html
      - ./app/lib/vendor/symfony/data/web/sf:/var/www/html/sf
      - symfony_cache:/var/www/cache
      - symfony_log:/var/www/log
    expose:
      - 80
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - bd
    environment:
      - PMA_HOST=bd
      - PMA_PORT=3306
    restart: unless-stopped

volumes:
  mariadb:
  symfony_cache:
  symfony_log:
