<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Editar diario') ?></h1>
</div>
<div id="editar">
<?php use_helper('Object') ?>

<?php echo form_tag('diario/update','name=formulario') ?>

<?php echo object_input_hidden_tag($diario, 'getId') ?>
<?php echo object_input_hidden_tag($diario, 'getProfesorId') ?>
<?php echo object_input_hidden_tag($diario, 'getAsignaturaId') ?>
<?php echo object_input_hidden_tag($diario, 'getEvaluacionId') ?>
<?php echo object_input_hidden_tag($diario, 'getGrupoId') ?>
<?php echo object_input_hidden_tag($diario, 'getFecha') ?>
<?php echo object_input_hidden_tag($diario, 'getActivo', array (
  'value' => true
  )); ?>

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos diario') ?></th>
</tr>
</thead>
<tbody>
<tr>
  <td class="nombres"><label><?php echo __('Profesor') ?>: </label></td>
  <td><?php echo $profesor->getNombre()?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Evaluacion') ?>: </label></td>
  <td><?php echo $evaluacion->getTitulo()?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Asignatura') ?>: </label></td>
  <td><?php echo $asignatura->getNombre()?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Grupo') ?>: </label></td>
  <td><?php echo $grupo->getNombre()?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Fecha') ?>: </label></td>
  <td><?php    //Obtenemos el formato para las fechas 
   if ($sf_user->getCulture() == 'es')
   {
      $formato = 'd-m-Y';   
   } 
   if ($sf_user->getCulture() == 'eu')
   {
      $formato = 'Y-m-d';   
   }  
   
   echo date($formato,strtotime($diario->getFecha()))?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Actividad') ?>: </label></td>
  <td><?php echo object_textarea_tag($diario, 'getActividad', array (
  'size' => '40x4',
)) ?></td>
</tr>
</tbody>
</table>
<div id="linea"></div>	
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<?php if ($diario->getId()): ?>
  <div class="delete"><?php echo link_to(__('Eliminar'), 'diario/delete?id='.$diario->getId(), 'post=true&confirm='.__('Are you sure?')) ?></div>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'diario/show?id='.$diario->getId()) ?></div>
<?php else: ?>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'diario/index?fecha='.strtotime($diario->getFecha())) ?></div>
<?php endif; ?>
</form>
</div>
</div>