<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Editar horario') ?></h1>
</div>

<div id="editar">

<?php use_helper('Object') ?>

<?php echo form_tag('horario/update', 'name = formulario') ?>

<?php echo object_input_hidden_tag($horario, 'getId') ?>
<?php echo input_hidden_tag('dia', $horario->getDia()) ?>
<?php echo input_hidden_tag('hora', $horario->getHora()) ?>
<?php echo object_input_hidden_tag($horario, 'getProfesorId', array (
  'value' => $profesor->getId()
  )) ?>
<?php echo object_input_hidden_tag($horario, 'getActivo', array (
  'value' => true
  )); ?>
<?php echo input_hidden_tag('crear', $crear); 

$d = new Criteria();
$d->addAscendingOrderByColumn(GrupoPeer::NOMBRE); 
?>

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos horario') ?></th>
</tr>
</thead>
<tbody>
<tr>

  <td class="nombres"><label><?php echo __('Profesor') ?>: </label></td><td><?php echo $profesor->getNombre(); ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Asignatura') ?>: </label></td><td><?php echo select_tag('asignatura_id', objects_for_select(
  AsignaturaPeer::doSelect($c),
  'getId',
  'getNombre',
  $horario->getAsignaturaId()
 ))?></td>
</tr>
<tr>
 
  <td class="nombres"><label><?php echo __('Grupo') ?>: </label></td><td><?php echo select_tag('grupo_id', objects_for_select(
  GrupoPeer::doSelect($d),
  'getId',
  'getNombre',
  $horario->getGrupoId()
 ))?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Dia') ?>: </label></td><td>
  <?php 
      include_component ('principal','dias', array (
      'dia' => $horario->getDia() 
      ));?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Hora') ?>: </label></td><td><?php  
      include_component ('principal','horas', array (
      'hora' => $horario->getHora() 
      ));?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Observaciones') ?>: </label></td><td><?php echo object_textarea_tag($horario, 'getObservaciones', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>
</form>

<div id="linea"></div>
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<?php if ($horario->getId()): ?>
  <div class="delete"><?php echo link_to(__('Eliminar'), 'horario/delete?id='.$horario->getId(), 'post=true&confirm='.__('Are you sure?')) ?></div>  
<?php endif; ?>
<div class="cancel"><?php echo link_to(__('Cancelar'), 'horario/completo') ?></div>


</div>
</div>
