<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Mover horario') ?></h1>
</div>

<div id="editar">

<?php use_helper('Object') ?>

<?php echo form_tag('horario/updatedia', 'name = formulario') ?>

<?php echo object_input_hidden_tag($horario, 'getId') ?>
    
<?php echo input_hidden_tag('crear', $crear); 

$d = new Criteria();
$d->addAscendingOrderByColumn(GrupoPeer::NOMBRE); 
?>

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos horario') ?></th>
</tr>
</thead>
<tbody>
<tr>

  <td class="nombres"><label><?php echo __('Profesor') ?>: </label></td><td><?php echo $profesor->getNombre(); ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Asignatura') ?>: </label></td><td><?php echo $horario->getAsignatura()->getNombre(); ?></td>
</tr>
<tr>
 
  <td class="nombres"><label><?php echo __('Grupo') ?>: </label></td><td><?php echo $horario->getGrupo()->getNombre(); ?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Dia') ?>: </label></td><td>
      <select name="dia">
      <?php
      for($x=1;$x<=5;$x++)
      {?>
          <option value="<?php echo $x; ?>"
          <?php
          if($horario->getDia() == $x)
          {
              echo "selected='selected'";
          } 
          echo ">";
      include_component ('principal','dias', array (
      'dia' => $x 
      ));
      echo "</option>";
      }
      ?>
      </select>
  </td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Hora') ?>: </label></td><td> 
    <select name="hora">
      <?php      
      for($x=0;$x<$maximo;$x++)
      {?>
          <option value="<?php echo $x; ?>"
          <?php
          if($horario->getHora() == $x)
          {
              echo "selected='selected'";
          } 
          echo ">";
      include_component ('principal','horas', array (
      'hora' => $x 
      ));
      echo "</option>";
      }
      ?>
      </select>  
  </td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Observaciones') ?>: </label></td><td><?php echo $horario->getObservaciones(); ?></td>
</tr>
</tbody>
</table>
</form>

<div id="linea"></div>
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<?php if ($horario->getId()): ?>
  <div class="delete"><?php echo link_to(__('Eliminar'), 'horario/delete?id='.$horario->getId(), 'post=true&confirm='.__('Are you sure?')) ?></div>  
<?php endif; ?>
<div class="cancel"><?php echo link_to(__('Cancelar'), 'horario/completo') ?></div>


</div>
</div>
