<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Visualizar horario') ?></h1>
</div>

<div id="mostrar">

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th id="sf_admin_list_th_id"><?php echo __('Datos horario') ?></th>
</tr>
</thead>
<tbody>
<tr>
<th><?php echo __('Id') ?>: </th>
<td class="i"><?php echo $horario->getId() ?></td>
</tr>
<tr>
<th><?php echo __('Profesor') ?>: </th>
<td class="p"><?php echo $profesor->getNombre() ?></td>
</tr>
<tr>
<th><?php echo __('Asignatura') ?>: </th>
<td class="i"><?php
      foreach ($asignaturas as $asignatura):
      if ($asignatura->getId() == $horario->getAsignaturaId())
      { 
          echo $asignatura->getNombre();
      }
      endforeach;
      ?>
      </td>
</tr>
<tr>
<th><?php echo __('Grupo') ?>: </th>
<td class="p"><?php
      foreach ($grupos as $grupo):
      if ($grupo->getId() == $horario->getGrupoId())
      { 
          echo $grupo->getNombre();
      }
      endforeach;
      ?></td>
</tr>
<tr>
<th><?php echo __('Dia') ?>: </th>
<td class="i"><?php 
      include_component ('principal','dias', array (
      'dia' => $horario->getDia() 
      ));?></td>
</tr>
<tr>
<th><?php echo __('Hora') ?>: </th>
<td class="p"><?php 
      include_component ('principal','horas', array (
      'hora' => $horario->getHora() 
      ));?></td>
</tr>
<tr>
<th><?php echo __('Observaciones') ?>: </th>
<td class="i"><?php echo $horario->getObservaciones() ?></td>
</tr>
<tr>
<th><?php echo __('Actualizado') ?>: </th>
<td class="p"><?php echo $horario->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>

<div id="linea"></div>
<div class="edit">
<?php echo link_to(__('Editar'), 'horario/edit?id='.$horario->getId()) ?>
</div>
<div class="edit">
<?php echo link_to(__('Mover día'), 'horario/editdia?id='.$horario->getId()) ?>
</div>
<div class="exit" style="margin-left: 15px;">
<?php echo link_to(__('Volver'), 'horario/completo') ?>
</div>

</div>
</div>
