<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Javascript') ?>
<?php echo javascript_tag("
  function imprimir()
  {
   window.print();
  }
") ?>
<?php
foreach ($alumnos as $alumno):
    $var = "im".$alumno->getId();
    echo javascript_tag("
    function imagen".$alumno->getId()."(ver) {
       document.getElementById('".$var."').style.visibility = ver;
       }
        ");
endforeach;
?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Listado del grupo') ?> <?php echo $grupo->getNombre(); ?> <?php echo __('en la evaluación:') ?> <?php echo $evaluacion->getTitulo(); ?>
<div class="imprimir" style="float: right; font-size: 9pt; font-weight: normal;">
   <?php echo link_to_function(__('Imprimir'), "imprimir()"); ?>
</div>
</h1>
</div>
<div id="listado">
<div id="warning"></div>
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Alumno') ?></th>
  <?php
  //Contar cuantos lunes, martes, .... hay desde el comienzo de la evaluacion hasta el final
  $lunes = 0;
  $martes = 0;
  $miercoles = 0;
  $jueves = 0;
  $viernes = 0;
  for($x = strtotime($evaluacion->getFechaini()); $x <= strtotime($evaluacion->getFechafin()); $x = strtotime("+1 day",$x))
  {
    $fecha = getdate($x);
    $dia = $fecha['wday'];
    switch ($dia)
    {   
      case 1:
          $lunes++;
          break;
      case 2:
          $martes++;
          break;
      case 3:
          $miercoles++;
          break;
      case 4:
          $jueves++;
          break;
      case 5:
          $viernes++;
          break;
     }
  }  
  //Termina el recuento de la evaluacion  
  
  //Restar el número de días festivos
        foreach ($festivos as $festivo):
          $fecha = getdate(strtotime($festivo->getFecha())); 
          $dia = $fecha['wday'];
          switch ($dia)
          {   
            case 1:
              $lunes--;
              break;
            case 2:
              $martes--;
              break;
            case 3:
              $miercoles--;
              break;
            case 4:
              $jueves--;
              break;
            case 5:
              $viernes--;
              break;
           }
        endforeach;
        //Termina resto de días festivos
  
    
  foreach ($asignaturas as $asignatura):?>
    <th><?php echo $asignatura->getNombre() ?></th>
  <?php
  endforeach; //asignatura 
  ?> 
  <th><?php echo __('Nota media') ?></th> 
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno):
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
      <?php
      $vis = "imagen".$alumno->getId()."('visible')";
      $oc = "imagen".$alumno->getId()."('hidden')";
      ?>
      <td class="alum"><img class="foto_alum" src="/images/iconos/camera_small.png" onmouseover="<?php echo $vis; ?>" onmouseout="<?php echo $oc; ?>" /><?php echo $alumno->getNombre() ?>
       <div id="im<?php echo $alumno->getId();?>" style="visibility:hidden;position:absolute;">
           <?php $ruta="/images/grupos/".$alumno->getGrupoId()."/".$alumno->getId().".jpg";?>
           <img src="<?php echo $ruta?>" />
       </div>
      </td>
      <?php
      $total = 0;
      $cont_total = 0;
      foreach ($asignaturas as $asignatura):
         $modif = false;
         foreach($notasev as $notaev):
             if ($notaev->getAlumnoId() == $alumno->getId() && $notaev->getEvaluacionId() == $evaluacion->getId() && $notaev->getAsignaturaId() == $asignatura->getId())
             {
                 $notamod = $notaev->getNota();
                 $modif = true;
             }
         endforeach;
        //Contar cuantas horas hay cada día de cada asignatura
        $horas_lunes = 0;
        $horas_martes = 0;
        $horas_miercoles = 0;
        $horas_jueves = 0;
        $horas_viernes = 0;
        foreach ($horarios as $horario):
        if ($asignatura->getId() == $horario->getAsignaturaId())
        {
          switch ($horario->getDia())
          {
            case 1:
              $horas_lunes++;
              break;
            case 2:
              $horas_martes++;
              break;
            case 3:
              $horas_miercoles++;
              break;
            case 4:
              $horas_jueves++;
              break;
            case 5:
              $horas_viernes++;
              break;      
          }    
        }
        endforeach; //horarios 
        //Termina el recuento de horas de cada día en cada asignatura
                
        $total_horas = ($lunes * $horas_lunes) + ($martes * $horas_martes) + ($miercoles * $horas_miercoles) + ($jueves * $horas_jueves) + ($viernes * $horas_viernes);

        //Contar el total de faltas sin justificar de la evaluación por cada asignatura y alumno 
        $faltas_alumno = 0;
        foreach ($faltas as $falta):
          if ($falta->getAlumnoId() == $alumno->getId() && $falta->getAsignaturaId() == $asignatura->getId() && $falta->getJustificado() == false)
          {
             $faltas_alumno++;
          } 
        endforeach; //faltas 
        //Termina recuento de faltas
        
        //Calcular la nota de faltas
        $maximo = $asignatura->getMaximofaltas();
        $horas_maximas = round(($total_horas * $maximo)/100);
        
        $evaluado = true;
        
        if ($faltas_alumno > $horas_maximas)
        {
          $evaluado = false;  
          $nota_faltas = 10;      
        }
        else
        {
          $nota_faltas = ($faltas_alumno * 10)/$horas_maximas; 
        }  
        //Termina el calculo de la nota de faltas
      
      //Comprobación de porcentajes 
      $porcentaje_cien = 0;
      $porcentaje = 0;
      $suma_porcentajes = 0;
      $error = 0;
      foreach($pruebas as $prueba):
       if($asignatura->getId() == $prueba->getAsignaturaId())
        {
         if ($prueba->getPorcentaje() != 100)
         {
           $suma_porcentajes = $suma_porcentajes + $prueba->getPorcentaje();
           $porcentaje = 1;
         }
         else
         {
           $porcentaje_cien = 1;         
         } 
        }  
      endforeach; //pruebas 
      
      if ($porcentaje_cien == true && $porcentaje == true)
      {
        echo javascript_tag (remote_function(array(
          'update' => 'warning',
          'url' => 'principal/warning?error=1'
          )));//No puede haber porcentajes de 100 y de menos de 100 (redireccionar a pagina de error)     
      }
      else if ($porcentaje == true && $suma_porcentajes != 100)
      { 
        echo javascript_tag (remote_function(array(
          'update' => 'warning',
          'url' => 'principal/warning?error=2'
          )));//Si sin porcentajes menores de 100 la suma tiene que ser 100 (redireccionar a pagina de error)
      } 
      //Sale de comprobación de porcentajes     
      $cont_prueba = 0;
      $suma_prueba = 0;
      $media = 0;
      
      foreach ($pruebas as $prueba):
       if($asignatura->getId() == $prueba->getAsignaturaId())
       {
        $porcen_prueba = $prueba->getPorcentaje();
        foreach ($notasprueba as $notaprueba):
          if ($notaprueba->getAlumnoId() == $alumno->getId() && $notaprueba->getPruebaId() == $prueba->getId())
          {
            if($notaprueba->getNota())
             {
              $nota = $notaprueba->getNota();
             }
             else
             {
              $nota = 0;
             }
            if($porcentaje_cien == true)
            {
              $suma_prueba = $suma_prueba + $nota;
              $cont_prueba = $cont_prueba + 1;
            }
            else
            {
                $suma_prueba = $suma_prueba + (($nota * $porcen_prueba)/100);
            }
          }
        endforeach; //notasprueba 
        
        if ($porcentaje_cien == true)
        {
         if($cont_prueba != 0)
         {
          $media =  $suma_prueba/$cont_prueba;
         }
         else
         {
          $media = 0;
         }
        }
        else
        {
        $media = $suma_prueba;        
        }
        ?>
        <?php
       } 
      endforeach; //pruebas 
      
      if (count($pruebas) == 0)
      {
        $media = 0;      
      }
      //Sacar la nota del comportamiento
      $nota_comportamiento = 0;
      foreach ($comportamientos as $comportamiento):
        if($alumno->getId() == $comportamiento->getAlumnoId() && $asignatura->getId() == $comportamiento->getAsignaturaId())
        {
          $nota_comportamiento = $comportamiento->getNota();
        }   
      endforeach; //comportamiento
      //Termina calculo de la nota de comportamiento

      if ($media != 0)
      {
        $media_asignatura = (($media * $asignatura->getPorcentajepruebas())/100) + ((($asignatura->getPorcentajefaltas() * 10)/100) - (($nota_faltas * $asignatura->getPorcentajefaltas())/100)) + (($nota_comportamiento * $asignatura->getPorcentajecomportamiento())/100);
      }
      else {
          $media_asignatura = 0;
      }
      if ($modif == true)
      {
        $total = $total + $notamod;
      }
      else
      {
        $total = $total + $media_asignatura;
      }
      $cont_total++;
      ?>
      <td><?php 
      if ($evaluado == false)
      {
        echo __('superado faltas - ');      
      }
      if ($modif == true)
      {
          echo number_format($notamod,2,',','.');
      }
      else
      {
        echo number_format($media_asignatura,2,',','.');
      }
      ?></td>
      <?php 
      endforeach; //asignatura 
      ?>
      <td><?php
      $media_total = $total/$cont_total;
      echo number_format($media_total,2,',','.'); ?></td>
</tr>
<?php
$x++; 
endforeach; //alumno 
?>
</tbody>
</table>

<div id="linea"></div>
<div class="exit">
<?php 
echo link_to(__('Volver'), 'listados/index'); 
?>
</div>
</div>
</div>
