<?php
// auto-generated by sfPropelAdmin
// date: 2016/09/08 08:48:21
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'sfGuardUser/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
