<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Date') ?> 

<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
  function enviar1()
  {
   document.formulario.otro.value = '1';
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Editar alumno') ?></h1>
</div>

<div id="editar">

<?php use_helper('Object') ?>

<?php echo form_tag('alumno/update', 'multipart=true name=formulario') ?>

<?php echo object_input_hidden_tag($alumno, 'getId') ?>

<?php echo input_hidden_tag('otro', 0) ?>


<?php echo object_input_hidden_tag($alumno, 'getActivo', array (
  'value' => true
  )); ?>

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos alumno') ?></th>
</tr>
</thead>
<tbody>
<tr>

  <td class="nombres"><label><?php echo __('Grupo') ?>: </label></td><td><?php 
  if (($sf_user->getAttribute('admin') == true || $sf_user->isSuperAdmin()) && $grupo_id == 0) 
  { 
  echo select_tag('grupo_id', objects_for_select(
  GrupoPeer::doSelect(new Criteria()),
  'getId',
  'getNombre',
  $alumno->getGrupoId()
 ));
  }
  else
  {
    echo input_hidden_tag('grupo_id', $grupo->getId()); 
    echo $grupo->getNombre();
  }?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Codigo') ?>: </label></td><td><?php echo object_input_tag($alumno, 'getCodigo', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Nombre') ?>: </label></td><td><?php echo object_input_tag($alumno, 'getNombre', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Email') ?>: </label></td><td><?php echo object_input_tag($alumno, 'getEmail', array (
  'size' => 50,
)) ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Observaciones') ?>: </label></td><td><?php echo object_textarea_tag($alumno, 'getObservaciones', array (
  'size' => '30x3',
)) ?></td>
</tr>

<tr>
  <td class="nombres"><label><?php echo __('Foto') ?>: </label></td><td><?php 
  if ($foto == "")
  {
    echo input_file_tag('foto');
  }
  else
  {
      ?>
      <div id="imagen">
      <div style="float: left;">
      <?php
      echo image_tag('/'.$dir.'/'.$foto,'style="width:100px;"');
      ?>
      </div>
      <div class="delete">
      <?php echo link_to_remote('Eliminar', array(
      'url' => 'alumno/imagendelete?id='.$alumno->getId().'&foto='.$foto,
      'update' => 'imagen',
      'confirm' => '¿Estás seguro?'));
      ?></div>
      </div>
      <?php
  }?></td>
</tr>
</tbody>
</table>
</form>

<div id="linea"></div>
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<div class="save">
<?php echo link_to_function(__('Guardar y añadir'), "enviar1()"); ?>
</div>
<?php if ($alumno->getId()): ?>
  <div class="delete"><?php echo link_to(__('Eliminar'), 'alumno/delete?id='.$alumno->getId(), 'post=true&confirm='.__('Are you sure?')) ?></div>
<?php endif; ?>
<?php if ($sf_user->getAttribute('admin') == true || $sf_user->isSuperAdmin()) 
{?>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'alumno/index') ?></div>
<?php 
}
else
{?>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'alumno/index?grupo_id='.$alumno->getGrupoId()) ?></div>
<?php 
}
?>

</div>
</div>
