<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Javascript') ?>

<?php
foreach ($alumnos as $alumno):
    $var = "im".$alumno->getId();
    echo javascript_tag("
    function imagen".$alumno->getId()."(ver) {
       document.getElementById('".$var."').style.visibility = ver;
       }
        ");
endforeach;
?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Alumnos') ?> 
<?php if ($sf_user->getAttribute('admin') == false && !$sf_user->isSuperAdmin()) 
{
  echo " del grupo ";
  foreach ($grupos as $grupo):
      if ($grupo->getId() == $grupo_id)
      {
          echo $grupo->getNombre();
      }
  endforeach;

  echo " (".count($alumnos).") "; 
  echo " (";
  echo __('Tutor');
  echo ": ";
  echo $tutor->getNombre();
  echo ")";
}

if ($grupo_id != 0)
{?>
<div class="imprimir" style="float: right; font-size: 9pt; font-weight: normal;">
   <?php echo link_to(__('Imprimir fotos'), 'alumno/fotos?grupo_id='.$grupo_id); ?>
</div>
    
<div class="imprimir" style="float: right; font-size: 9pt; font-weight: normal;">
   <?php echo link_to(__('Imprimir datos'), 'alumno/datos?grupo_id='.$grupo_id); ?>
</div>
<?php
}
?>
</h1>
</div>

<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Codigo') ?></th>
  <th><?php echo __('Nombre') ?></th>
  <th><?php echo __('Grupo') ?></th>
  <th><?php echo __('Acciones') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
    <?php
   $vis = "imagen".$alumno->getId()."('visible')";
   $oc = "imagen".$alumno->getId()."('hidden')";
   ?>
      <td><?php echo $alumno->getCodigo() ?></td>
      <td><img src="/itutor/images/iconos/camera_small.png" onmouseover="<?php echo $vis; ?>" onmouseout="<?php echo $oc; ?>" /><?php echo $alumno->getNombre() ?>
       <div id="im<?php echo $alumno->getId();?>" style="visibility:hidden;position:absolute;">
           <?php $ruta="/itutor/images/grupos/".$alumno->getGrupoId()."/".$alumno->getId().".jpg";?>
           <img src="<?php echo $ruta?>" style="width:100px;" />
       </div>
      </td>
      <td><?php 
      foreach ($grupos as $grupo):  
       if ($grupo->getId() == $alumno->getGrupoId())
       {    
          echo $grupo->getNombre();
       }
       endforeach;?></td>
      <td><?php
         echo link_to (image_tag('/images/iconos/view1.png'), 'alumno/show?id='.$alumno->getId());
         echo link_to (image_tag('/images/iconos/edit1.png'), 'alumno/edit?id='.$alumno->getId());
         echo link_to (image_tag('/images/iconos/delete1.png'), 'alumno/delete?id='.$alumno->getId(), 'post=true&confirm='.__('Are you sure?'));
         ?>
      </td>
  </tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>

<div id="linea"></div>
<div class="add">
<?php echo link_to (__('Nuevo'), 'alumno/create?grupo_id='.$grupo_id) ?>
</div>
<?php if ($sf_user->getAttribute('admin') == true || $sf_user->isSuperAdmin()) 
{?>
<div class="exit">
<?php echo link_to (__('Volver'), 'alumno/index') ?>
</div>
<?php
}
?>

</div>
</div>
