<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Horas del perfil') ?> <?php echo$perfil->getNombre() ?></h1>
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Id') ?></th>
  <th><?php echo __('Tramo') ?></th>
  <th><?php echo __('Activo') ?></th>
  <th><?php echo __('Actualizado') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($horasperfil as $horaperfil):
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
} 
?>
<tr class="<?php echo $fila ?>">
    <td><?php echo link_to($horaperfil->getId(), 'perfil/perfilhoraedit?id='.$horaperfil->getId().'&perfil='.$perfil->getId()) ?></td>
      <td><?php 
      foreach ($horas as $hora):
        if($hora->getId() == $horaperfil->getHoraId())
        {
          echo $hora->getTramo();
        }
      endforeach;      
      ?></td>
      <td><?php echo $horaperfil->getActivo() ?></td>
      <td><?php echo $horaperfil->getUpdatedAt() ?></td>
</tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>
<div id="linea"></div>	
<div class="add">
<?php echo link_to (__('Nuevo'), 'perfil/perfilhoracreate?perfil='.$perfil->getId()) ?>
</div>
<div class="exit">
<?php echo link_to (__('Volver'), 'perfil/list') ?>
</div>
</div>
</div>

