#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          mysql://root:@localhost/dbname

all:
  itutor:
    class:          sfPropelDatabase
    param:
      phptype:            mysql     # Database vendor
      hostspec:           bd
      database:           itutor
      username:           itutor
      password:           '12345Abcde'
      encoding:           utf8      # Default charset for table creation
      persistent:         true      # Use persistent connections

  propel:
    class:          sfPropelDatabase
    param:
      phptype:            mysql     # Database vendor
      hostspec:           bd
      database:           itutor
      username:           itutor
      password:           '12345Abcde'
      encoding:           utf8      # Default charset for table creation
      persistent:         true      # Use persistent connections
