<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Notas de alumnos de') ?> <?php echo $grupo->getNombre()?></h1>
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Alumno') ?></th>
  <th><?php echo __('Nota') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>

<tr class="<?php echo $fila ?>">
   <td><?php echo $alumno->getNombre() ?></td>
   <td><?php 
   foreach ($notas as $nota):
     if ($nota->getAlumnoId() == $alumno->getId())
     {
        $n = str_replace(".",",",$nota->getNota());
        echo $n;     
     }
   endforeach;   
   ?></td>
</tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>

<div id="linea"></div>	
<div class="edit"> 
<?php echo link_to(__('Editar'), 'prueba/notasedit?prueba='.$prueba->getId().'&grupo='.$grupo->getId().'&grupoid='.$grupoid.'&fecha='.strtotime($prueba->getFecha())) ?>
</div>
<div class="exit">
<?php
 if ($grupoid == 0)
 { 
    echo link_to (__('Volver'), 'prueba/list?grupo=0&grupoid=0&fecha='.$fecha);
 }  
 else
 {
   echo link_to (__('Volver'), 'prueba/listado?grupo='.$grupo->getId().'&dia='.$prueba->getDia().'&hora='.$prueba->getHora().'&asignatura='.$prueba->getAsignaturaId().'&grupoid='.$grupoid.'&fecha='.strtotime($prueba->getFecha()));
 }
?>
</div>

</div>
</div>
