<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Pruebas') ?></h1>
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Evaluación') ?></th>
  <th><?php echo __('Asignatura') ?></th>
  <th><?php echo __('Grupo') ?></th>
  <th><?php echo __('Descripción') ?></th>
  <th><?php echo __('Dia') ?></th>
  <th><?php echo __('Hora') ?></th>
  <th><?php echo __('Fecha') ?></th>
  <th><?php echo __('Notas') ?></th>
  <th><?php echo __('Acciones') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($pruebas as $prueba): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
      <td><?php 
      foreach ($evaluaciones as $evaluacion):
        if ($evaluacion->getId() == $prueba->getEvaluacionId())
        {
          echo $evaluacion->getTitulo();        
        }      
      endforeach;?></td>
      <td><?php 
      foreach ($asignaturas as $asignatura):
        if ($asignatura->getId() == $prueba->getAsignaturaId())
        {
          echo $asignatura->getNombre();  
        }      
      endforeach;?></td>
      <td><?php 
      $obj_grupo = $prueba->getGrupo(); 
      if ($obj_grupo)
      {
          echo $obj_grupo->getNombre();  
      }
      ?></td>
      <td><?php
          echo $prueba->getObservaciones();
      ?></td>
      <td><?php 
      include_component ('principal','dias', array (
      'dia' => $prueba->getDia() 
      ));?></td>
      <td><?php 
      include_component ('principal','horas', array (
      'hora' => $prueba->getHora() 
      ));?></td>
      <td><?php 
      if ($sf_user->getCulture() == 'es')
      {  
        echo date('d-m-Y',strtotime($prueba->getFecha())); 
      }
      if ($sf_user->getCulture() == 'eu')
      {  
        echo date('Y-m-d',strtotime($prueba->getFecha())); 
      } ?></td>
      <td><?php 
      if ($grupo == 0)
      {
        foreach ($horarios as $horario):
          if ($horario->getAsignaturaId() == $prueba->getAsignaturaId())
          {
            if ($prueba->getGrupo())
            {
                $vargrupo = $prueba->getGrupoId();
            } 
            else
            {
                
               $vargrupo = $horario->getGrupoId();
            }
            echo link_to('Introducir Notas', 'prueba/notasedit?prueba='.$prueba->getId().'&grupo='.$vargrupo.'&grupoid='.$vargrupo.'&fecha='.strtotime($prueba->getFecha()));
          } 
        endforeach;
      }
      ?> 
      </td>
      <td>
      <?php
         echo link_to (image_tag('/images/iconos/view1.png'), 'prueba/show?id='.$prueba->getId().'&grupoid='.$prueba->getGrupoId().'&fecha='.$fecha);
         echo link_to (image_tag('/images/iconos/edit1.png'), 'prueba/edit?id='.$prueba->getId().'&grupoid='.$prueba->getGrupoId().'&fecha='.strtotime($prueba->getFecha()));
         echo link_to (image_tag('/images/iconos/delete1.png'), 'prueba/delete?id='.$prueba->getId().'&fecha='.strtotime($prueba->getFecha()), 'post=true&confirm='.__('Are you sure?'));
         ?>
      </td>
  </tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>

<div id="linea"></div>	


<div class="exit">
<?php 
echo link_to(__('Volver'), 'prueba/index?fecha='.$fecha); 
?>
</div>
</div>
</div>
