<?php
// auto-generated by sfPhpConfigHandler
// date: 2016/09/10 12:32:45
ini_set('log_errors', '1');
ini_set('arg_separator.output', '&amp;');
if (ini_get('session.auto_start') != false)
{
  sfLogger::getInstance()->warning('{sfPhpConfigHandler} php.ini "session.auto_start" key is better set to "false" (current value is "\'0\'" - php.ini location: "/etc/php/5.6/apache2/php.ini").');
}

