<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/11/02 17:21:22
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
