<?php
// auto-generated by sfPropelAdmin
// date: 2016/09/08 08:53:29
?>
<?php echo form_tag('grupoevaluacion/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($grupoevaluacion, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('grupoevaluacion[grupo_id]', __($labels['grupoevaluacion{grupo_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grupoevaluacion{grupo_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupoevaluacion{grupo_id}')): ?>
    <?php echo form_error('grupoevaluacion{grupo_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($grupoevaluacion, 'getGrupoId', array (
  'related_class' => 'Grupo',
  'control_name' => 'grupoevaluacion[grupo_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('grupoevaluacion[evaluacion_id]', __($labels['grupoevaluacion{evaluacion_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grupoevaluacion{evaluacion_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupoevaluacion{evaluacion_id}')): ?>
    <?php echo form_error('grupoevaluacion{evaluacion_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($grupoevaluacion, 'getEvaluacionId', array (
  'related_class' => 'Evaluacion',
  'control_name' => 'grupoevaluacion[evaluacion_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('grupoevaluacion[activo]', __($labels['grupoevaluacion{activo}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grupoevaluacion{activo}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupoevaluacion{activo}')): ?>
    <?php echo form_error('grupoevaluacion{activo}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_checkbox_tag($grupoevaluacion, 'getActivo', array (
  'control_name' => 'grupoevaluacion[activo]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('grupoevaluacion[updated_at]', __($labels['grupoevaluacion{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('grupoevaluacion{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('grupoevaluacion{updated_at}')): ?>
    <?php echo form_error('grupoevaluacion{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($grupoevaluacion, 'getUpdatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'grupoevaluacion[updated_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('grupoevaluacion' => $grupoevaluacion)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($grupoevaluacion->getId()): ?>
<?php echo button_to(__('delete'), 'grupoevaluacion/delete?id='.$grupoevaluacion->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
