<?php
// auto-generated by sfPropelAdmin
// date: 2016/09/08 08:53:29
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupoevaluacion/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'grupoevaluacion/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'grupoevaluacion/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_grupo_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupoevaluacion/sort') == 'grupo_id'): ?>
      <?php echo link_to(__('Grupo'), 'grupoevaluacion/list?sort=grupo_id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Grupo'), 'grupoevaluacion/list?sort=grupo_id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_evaluacion_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupoevaluacion/sort') == 'evaluacion_id'): ?>
      <?php echo link_to(__('Evaluacion'), 'grupoevaluacion/list?sort=evaluacion_id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Evaluacion'), 'grupoevaluacion/list?sort=evaluacion_id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_activo">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupoevaluacion/sort') == 'activo'): ?>
      <?php echo link_to(__('Activo'), 'grupoevaluacion/list?sort=activo&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Activo'), 'grupoevaluacion/list?sort=activo&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_updated_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/grupoevaluacion/sort') == 'updated_at'): ?>
      <?php echo link_to(__('Updated at'), 'grupoevaluacion/list?sort=updated_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/grupoevaluacion/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Updated at'), 'grupoevaluacion/list?sort=updated_at&type=asc') ?>
      <?php endif; ?>
          </th>
