<?php
// auto-generated by sfPropelAdmin
// date: 2016/09/08 08:53:29
?>
    <td><?php echo link_to($grupoevaluacion->getId() ? $grupoevaluacion->getId() : __('-'), 'grupoevaluacion/edit?id='.$grupoevaluacion->getId()) ?></td>
    <td><?php echo $grupoevaluacion->getGrupoId() ?></td>
      <td><?php echo $grupoevaluacion->getEvaluacionId() ?></td>
      <td><?php echo $grupoevaluacion->getActivo() ? image_tag(sfConfig::get('sf_admin_web_dir').'/images/tick.png') : '&nbsp;' ?></td>
      <td><?php echo ($grupoevaluacion->getUpdatedAt() !== null && $grupoevaluacion->getUpdatedAt() !== '') ? format_date($grupoevaluacion->getUpdatedAt(), "f") : '' ?></td>
  