<?php
// auto-generated by sfPropelAdmin
// date: 2016/09/08 08:53:29
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit grupoevaluacion', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('grupoevaluacion/edit_header', array('grupoevaluacion' => $grupoevaluacion)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('grupoevaluacion/edit_messages', array('grupoevaluacion' => $grupoevaluacion, 'labels' => $labels)) ?>
<?php include_partial('grupoevaluacion/edit_form', array('grupoevaluacion' => $grupoevaluacion, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('grupoevaluacion/edit_footer', array('grupoevaluacion' => $grupoevaluacion)) ?>
</div>

</div>
