<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php use_helper('Javascript') ?>
<?php use_helper('Object') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<?php
foreach ($alumnos as $alumno):
    $var = "im".$alumno->getId();
    echo javascript_tag("
    function imagen".$alumno->getId()."(ver) {
       document.getElementById('".$var."').style.visibility = ver;
       }
        ");
endforeach;
?>

<?php echo form_tag('comportamiento/updateall','name=formulario') ?>

<?php echo input_hidden_tag('grupoid', $grupo->getId()) ?>
<?php echo input_hidden_tag('asignaturaid', $asignatura->getId()) ?>
<?php echo input_hidden_tag('evaluacionid', $evaluacion->getId()) ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Comportamientos del grupo') ?> <?php echo $grupo->getNombre() ?> <?php echo __(' en la asignatura '); ?><?php echo $asignatura->getNombre() ?></h1>
<h2><?php echo $evaluacion->getTitulo(); ?></h2>
</div>
<div id="listado">
<?php
if (!$comportamientos)
{
  echo link_to(__('Generar listado'),'comportamiento/generar?asig='.$asignatura->getId().'&ev='.$evaluacion->getId().'&grupo='.$grupo->getId());
} 
else
{
    echo link_to(__('Regenerar listado'),'comportamiento/regenerar?asig='.$asignatura->getId().'&ev='.$evaluacion->getId().'&grupo='.$grupo->getId());

?>
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Codigo') ?></th>
  <th><?php echo __('Nombre') ?></th>
  <th><?php echo __('Nota') ?></th>
  <th><?php echo __('Observaciones') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno):
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
    <?php
     $vis = "imagen".$alumno->getId()."('visible')";
     $oc = "imagen".$alumno->getId()."('hidden')";
     ?>
      <td><?php echo $alumno->getCodigo() ?></td>
      <td><img src="/images/iconos/camera_small.png" onmouseover="<?php echo $vis; ?>" onmouseout="<?php echo $oc; ?>" /><?php echo $alumno->getNombre() ?>
       <div id="im<?php echo $alumno->getId();?>" style="visibility:hidden;position:absolute;">
           <?php $ruta="/images/grupos/".$alumno->getGrupoId()."/".$alumno->getId().".jpg";?>
           <img src="<?php echo $ruta?>" />
       </div>
      </td>
      <?php
      foreach ($comportamientos as $comportamiento):
          if ($comportamiento->getAlumnoId() == $alumno->getId())
          {
          ?>
          <td><?php echo input_tag('nota'.$comportamiento->getId(),str_replace(".",",",$comportamiento->getNota()),'size=10'); ?></td>
          <td><?php echo textarea_tag('observaciones'.$comportamiento->getId(),$comportamiento->getObservaciones(),'size=30x2'); ?></td>
          <?php
          }
      endforeach;
          ?>
  </tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>
<?php
}
?>
<div id="linea"></div>
<div class="guardar">
<?php echo link_to_function(__('Guardar cambios'), "enviar()", 'style="color: red;"'); ?>
</div>	
<div class="exit">
<?php 
echo link_to(__('Volver'), 'comportamiento/index'); 
?>
</div>
</div>	
</div>
</form>
