<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2008/03/17 11:40:14
?>
<?php

/**
 * hora actions.
 *
 * @package    gesal
 * @subpackage hora
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class horaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('hora', 'list');
  }

  public function executeList()
  {
    $this->horas = HoraPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->hora = HoraPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->hora);
  }

  public function executeCreate()
  {
    $this->hora = new Hora();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->hora = HoraPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->hora);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $hora = new Hora();
    }
    else
    {
      $hora = HoraPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($hora);
    }

    $hora->setId($this->getRequestParameter('id'));
    $hora->setTramo($this->getRequestParameter('tramo'));
    $hora->setDescanso($this->getRequestParameter('descanso', 0));
    $hora->setDescripcion($this->getRequestParameter('descripcion'));
    $hora->setActivo($this->getRequestParameter('activo', 0));

    $hora->save();

    $this->getUser()->setAttribute('horas',true); 
    
    return $this->redirect('hora/list');
  }

  public function executeDelete()
  {
    $hora = HoraPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($hora);

    $hora->delete();
    
    $horas = HoraPeer::doSelect(new Criteria());
        
    if (count($horas) > 0)
    {
      $this->getUser()->setAttribute('horas',true);        
    }
    else
    {
      $this->getUser()->setAttribute('horas',false);
    }

    return $this->redirect('hora/list');
  }
}
