<?php
// auto-generated by sfPropelCrud
// date: 2010/09/10 14:11:55
?>
<?php

/**
 * grupoevaluacion actions.
 *
 * @package    itutor
 * @subpackage grupoevaluacion
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class grupoevaluacionActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('grupoevaluacion', 'list');
  }

  public function executeList()
  {
    $this->grupoevaluacions = GrupoevaluacionPeer::doSelect(new Criteria());

    $c = new Criteria();
    $c->addAscendingOrderByColumn(GrupoevaluacionPeer::GRUPO_ID);

    $this->gruposev = GrupoevaluacionPeer::doSelect($c);

    $this->grupos = GrupoPeer::doSelect(new Criteria());

    $this->evaluaciones = EvaluacionPeer::doSelect(new Criteria());

    $this->profesores = ProfesorPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->grupoevaluacion = GrupoevaluacionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->grupoevaluacion);
  }

  public function executeCreate()
  {
    $this->grupoevaluacion = new Grupoevaluacion();

    $this->setTemplate('edit');
  }

  public function executeEdit()
  {
    $this->grupoevaluacion = GrupoevaluacionPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->grupoevaluacion);
  }

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $grupoevaluacion = new Grupoevaluacion();
    }
    else
    {
      $grupoevaluacion = GrupoevaluacionPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($grupoevaluacion);
    }

    $grupoevaluacion->setId($this->getRequestParameter('id'));
    $grupoevaluacion->setGrupoId($this->getRequestParameter('grupo_id') ? $this->getRequestParameter('grupo_id') : null);
    $grupoevaluacion->setEvaluacionId($this->getRequestParameter('evaluacion_id') ? $this->getRequestParameter('evaluacion_id') : null);
    $grupoevaluacion->setActivo($this->getRequestParameter('activo', 0));

    $grupoevaluacion->save();

    return $this->redirect('grupoevaluacion/list');
  }

  public function executeDelete()
  {
    $grupoevaluacion = GrupoevaluacionPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($grupoevaluacion);

    $grupoevaluacion->delete();

    return $this->redirect('grupoevaluacion/list');
  }
}
