<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Javascript') ?>
<?php use_helper('Object') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<?php echo form_tag('diario/updateall','name=formulario') ?>


<?php echo input_hidden_tag('profesorid', $profesor->getId()) ?>
<?php echo input_hidden_tag('grupoid', $grupo->getId()) ?>
<?php echo input_hidden_tag('asignaturaid', $asignatura->getId()) ?>
<?php echo input_hidden_tag('evaluacionid', $evaluacion->getId()) ?>
<?php echo input_hidden_tag('opcion', $opcion) ?>
<?php echo input_hidden_tag('fecha', $fecha[0]) ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Diario del grupo') ?> <?php echo $grupo->getNombre()?> <?php echo __('en la asignatura de') ?> <?php echo $asignatura->getNombre()?></h1>
<h2><?php echo $evaluacion->getTitulo()?></h2>
</div>
<div id="listado">
<?php 
$actual = $fecha;
if (count($diarios) == 0)
{
  echo link_to(__('Generar diario'),'diario/generar?fecha='.$fecha[0].'&ev='.$evaluacion->getId().'&opcion='.$opcion); 
}
else
{
  echo link_to(__('Regenerar diario'),'diario/regenerar?fecha='.$fecha[0].'&ev='.$evaluacion->getId().'&opcion='.$opcion);

?> 
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Fecha') ?></th>
  <th><?php echo __('Número de horas') ?></th>
  <th><?php echo __('Actividad') ?></th>
  <th>
      <div style="float: right;">
      <div class="guardar">
      <?php echo link_to_function(__('Guardar cambios'), "enviar()", 'style="color: red;"'); ?>
      </div>
      <div class="volvercal">
      <?php echo link_to (__('Volver al calendario'), 'diario/list?fecha='.$actual[0]) ?>
      </div>
      <div class="imprimir">
      <?php echo link_to (__('Imprimir'), 'diario/imprimir?grupo='.$grupo->getId().'&asig='.$asignatura->getId().'&ev='.$evaluacion->getId().'&fecha='.$actual[0].'&prof='.$profesor->getId()) ?>
      </div>
      <div class="imprimir" style="float: right;">
      <?php echo link_to (__('Imprimir UD'), 'diario/imprimirud?grupo='.$grupo->getId().'&asig='.$asignatura->getId().'&ev='.$evaluacion->getId().'&fecha='.$actual[0].'&prof='.$profesor->getId()) ?>
      </div>
      </div>
  </th>
</tr>
</thead>
<tbody>
<?php 
echo form_tag('diario/update','name=formulario');

$x=1;

foreach ($diarios as $diario):
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>"> 
 <?php $fecha = getdate(strtotime($diario->getFecha())); ?>
<td>
    <?php 
        //Obtenemos el formato para las fechas 
        if ($sf_user->getCulture() == 'es')
        {  
          echo link_to(date('d-m-Y',strtotime($diario->getFecha())),'diario/show?id='.$diario->getId());
        }
        if ($sf_user->getCulture() == 'eu')
        {  
          echo link_to(date('Y-m-d',strtotime($diario->getFecha())),'diario/show?id='.$diario->getId()); 
        }  
    ?>           
</td>
<td style="padding-left: 15px;">
      <?php 
      if ($fecha['wday'] >= 1 && $fecha['wday'] <= 5 && $horas[$fecha['wday']] != 0)
      {
        echo $horas[$fecha['wday']];
      }
      ?>
      <?php
      echo " "; 
      if ($horas[$fecha['wday']] == 1)
      {
        echo __('hora');
      }
      else
      {
        echo __('horas'); 
      }
      ?>
</td> 
<td>
      <?php echo textarea_tag('actividad'.$diario->getId(), $diario->getActividad(), 'size=80x4'); ?>
</td>
<td>
      <?php echo textarea_tag('udidactica'.$diario->getId(), $diario->getUdidactica(), 'size=30x4'); ?>
      <?php echo __('UD'); ?>
</td>
</tr>
<?php
$x++; 
endforeach; 
?>
</form>
</tbody>
</table>
<?php
} 
?>
<div id="linea"></div>	
<div class="guardar">
<?php echo link_to_function(__('Guardar cambios'), "enviar()", 'style="color: red;"'); ?>
</div>
<div class="volvercal">
<?php echo link_to (__('Volver al calendario'), 'diario/index?fecha='.$actual[0]) ?>
</div>
<div class="imprimir">
<?php echo link_to (__('Imprimir'), 'diario/imprimir?grupo='.$grupo->getId().'&asig='.$asignatura->getId().'&ev='.$evaluacion->getId().'&fecha='.$actual[0].'&prof='.$profesor->getId()) ?>
</div>
<div class="imprimir">
<?php echo link_to (__('Imprimir UD'), 'diario/imprimirud?grupo='.$grupo->getId().'&asig='.$asignatura->getId().'&ev='.$evaluacion->getId().'&fecha='.$actual[0].'&prof='.$profesor->getId()) ?>
</div>
</div>
</div>

<?php echo input_hidden_tag('fecha', $actual[0]); ?>

</form>
