<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Grupos') ?></h1>
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Id') ?></th>
  <th><?php echo __('Nombre') ?></th> 
  <th><?php echo __('Descripción') ?></th>
  <th><?php echo __('Tutor') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($grupos as $grupo): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
    <td><?php echo link_to($grupo->getId(), 'grupo/show?id='.$grupo->getId()) ?></td>
      <td><?php echo $grupo->getNombre() ?></td>
      <td><?php echo $grupo->getDescripcion() ?></td>
      <td><?php 
      foreach ($profesores as $profesor):
       if ($profesor->getId() == $grupo->getProfesorId())
       {
          echo $profesor->getNombre(); 
       }
      endforeach;      
      ?></td>
  </tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>
<div id="linea"></div>
<div class="add">
<?php echo link_to (__('Nuevo'), 'grupo/create') ?>
</div>
</div>
</div>
