<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Horario de') ?> <?php echo $sf_user->getAttribute('nombre'); ?></h1>
</div>
<div id="horario">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Horas') ?></th>
  <th><?php echo __('Lunes') ?></th>
  <th><?php echo __('Martes') ?></th>
  <th><?php echo __('Miércoles') ?></th>
  <th><?php echo __('Jueves') ?></th>
  <th><?php echo __('Viernes') ?></th>
</tr>
</thead>
<tbody>
<?php
$y = 0;
$hora = 0;
$primera = "i";
$segunda = "p";
for($hora;$hora<count($horas);$hora++)
{
 //if ($hora % 2 ==0)
 //{
 //  $x = $primera;
 //  $primera = $segunda;
 //  $segunda = $x;
 //}
?>
 <?php $y++; ?>
 <tr>
    <th class="<?php
    if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
    ?>">
    <?php include_component('principal','horas',array(
     'hora' => $hora
     ));  
      
     ?> 
      </th>
      <td class="<?php 
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>"><?php
      $encontrado = false;
      foreach ($horarios as $horario):
        if ($horario->getDia() == 1 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'horario/show?id='.$horario->getId());
          $encontrado = true;
        }
       
      endforeach;
        if ($encontrado == false && $horas[$hora]->getDescanso() == false)
      {
           echo link_to(image_tag('/images/iconos/add.png','style="height:16px;"'), 'horario/create?dia=1'.'&hora='.$hora);

      }
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>"><?php
      $encontrado = false;
      foreach ($horarios as $horario):
        if ($horario->getDia() == 2 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
         echo link_to($asig_nombre. "<br />". $grupo_nombre, 'horario/show?id='.$horario->getId());
          $encontrado = true;
        }
        
      endforeach;
        if ($encontrado == false && $horas[$hora]->getDescanso() == false)
      {
           echo link_to(image_tag('/images/iconos/add.png','style="height:16px;"'), 'horario/create?dia=2'.'&hora='.$hora);

      }
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>"><?php
      $encontrado = false;
      foreach ($horarios as $horario):
        if ($horario->getDia() == 3 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'horario/show?id='.$horario->getId());
          $encontrado = true;
        }
       
      endforeach;
        if ($encontrado == false && $horas[$hora]->getDescanso() == false)
      {
           echo link_to(image_tag('/images/iconos/add.png','style="height:16px;"'), 'horario/create?dia=3'.'&hora='.$hora);

      }
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>"><?php
      $encontrado = false;
      foreach ($horarios as $horario):
        if ($horario->getDia() == 4 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
         echo link_to($asig_nombre. "<br />". $grupo_nombre, 'horario/show?id='.$horario->getId());
          $encontrado = true;
        }
        
      endforeach;
        if ($encontrado == false && $horas[$hora]->getDescanso() == false)
      {
           echo link_to(image_tag('/images/iconos/add.png','style="height:16px;"'), 'horario/create?dia=4'.'&hora='.$hora);

      }
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>"><?php
      $encontrado = false;
      foreach ($horarios as $horario):
        if ($horario->getDia() == 5 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
         echo link_to($asig_nombre. "<br />". $grupo_nombre, 'horario/show?id='.$horario->getId());
         $encontrado = true;

        }
          
      endforeach;
      if ($encontrado == false && $horas[$hora]->getDescanso() == false)
      {
          echo link_to(image_tag('/images/iconos/add.png','style="height:16px;"'), 'horario/create?dia=5'.'&hora='.$hora);
      }
      ?></td>
  </tr>
<?php
//if ($hora % 2 ==0)
// {
//   $x = $primera;
//   $primera = $segunda;
//   $segunda = $x;
// }
}?>
</tbody>
</table>
</div>
</div>

