<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Horario') ?></h1><h2><?php echo link_to ('Ver horario completo', 'horario/completo') ?></h2> 
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Id') ?></th>
  <th><?php echo __('Profesor') ?></th>
  <th><?php echo __('Asignatura') ?></th>
  <th><?php echo __('Grupo') ?></th>
  <th><?php echo __('Dia') ?></th>
  <th><?php echo __('Hora') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($horarios as $horario): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
    <td><?php echo link_to($horario->getId(), 'horario/show?id='.$horario->getId()) ?></td>
      <td><?php echo $profesor->getNombre() ?></td>
      <td><?php
      foreach ($asignaturas as $asignatura):
      if ($asignatura->getId() == $horario->getAsignaturaId())
      { 
          echo $asignatura->getNombre();
      }
      endforeach;
      ?></td>
      <td><?php
      foreach ($grupos as $grupo):
      if ($grupo->getId() == $horario->getGrupoId())
      { 
          echo $grupo->getNombre();
      }
      endforeach;
      ?></td>
      <td><?php 
      include_component ('principal','dias', array (
      'dia' => $horario->getDia() 
      ));?></td>
      <td><?php 
      include_component ('principal','horas', array (
      'hora' => $horario->getHora() 
      ));?></td>
  </tr>
<?php
$x++; 
endforeach; ?>
</tbody>
</table>

<div id="linea"></div>	
<div class="add">
<?php echo link_to (__('Nuevo'), 'horario/create') ?>
</div>
</div>
</div>
