<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Javascript') ?>

<?php echo javascript_tag("
  function imprimir()
  {
   window.print();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Alumnos') ?> 
<?php if ($sf_user->getAttribute('admin') == false && !$sf_user->isSuperAdmin()) 
{
  echo " del grupo ";
  echo $alumnos[0]->getGrupo()->getNombre();
  echo " (".count($alumnos).") "; 
  echo " (";
  echo __('Tutor');
  echo ": ";
  echo $tutor->getNombre();
  echo ")";
}?>
    
<div class="imprimir" style="float: right; font-size: 9pt; font-weight: normal;">
   <?php echo link_to_function(__('Imprimir'), "imprimir()"); ?>
</div>

</h1>
</div>

<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Codigo') ?></th>
  <th><?php echo __('Nombre') ?></th>
  <th><?php echo __('Observaciones') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
      <td><?php echo $alumno->getCodigo() ?></td>
      <td><?php echo $alumno->getNombre() ?></td>
      <td><?php echo $alumno->getObservaciones(); ?></td>
  </tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>
</div>
</div>
