<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Editar grupo - evaluación') ?></h1>
</div>
<div id="editar">

<?php use_helper('Object') ?>

<?php echo form_tag('grupoevaluacion/update', 'name=formulario') ?>

<?php echo object_input_hidden_tag($grupoevaluacion, 'getId') ?>
<?php echo object_input_hidden_tag($grupoevaluacion, 'getActivo', array (
  'value' => true
  ));
  ?>

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos grupo - evaluacion') ?></th>
</tr>
</thead>
<tbody>
<tr>
  <td class="nombres"><label><?php echo __('Grupo') ?>: </label></td><td><?php
  $c = new Criteria();
  $c->addAscendingOrderByColumn(GrupoPeer::NOMBRE);

  echo select_tag('grupo_id', objects_for_select(
  GrupoPeer::doSelect($c),
  'getId',
  'getNombre',
  $grupoevaluacion->getGrupoId()
 ))?></td>
</tr>

<tr>
  <td class="nombres"><label><?php echo __('Evaluación') ?>: </label></td><td><?php
  $c = new Criteria();
  $c->addAscendingOrderByColumn(EvaluacionPeer::ID);

  echo select_tag('evaluacion_id', objects_for_select(
  EvaluacionPeer::doSelect($c),
  'getId',
  'getTitulo',
  $grupoevaluacion->getEvaluacionId()
 ))?></td>
</tr>

<tr>

  <td class="nombres"><label><?php echo __('Activo') ?>: </label></td><td><?php echo object_checkbox_tag($grupoevaluacion, 'getActivo', array (
)) ?></td>
</tr>
</tbody>
</table>

<div id="linea"></div>
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<?php if ($grupoevaluacion->getId()): ?>
  <div class="delete"><?php echo link_to(__('Eliminar'), 'grupoevaluacion/delete?id='.$grupoevaluacion->getId(), 'post=true&confirm='.__('Are you sure?')) ?></div>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'grupoevaluacion/show?id='.$grupoevaluacion->getId()) ?></div>
<?php else: ?>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'grupoevaluacion/list') ?></div>
<?php endif; ?>
</form>
</div>
</div>