<?php
// auto-generated by sfPropelCrud
// date: 2010/09/10 14:11:55
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $grupoevaluacion->getId() ?></td>
</tr>
<tr>
<th>Grupo: </th>
<td><?php echo $grupoevaluacion->getGrupoId() ?></td>
</tr>
<tr>
<th>Evaluacion: </th>
<td><?php echo $grupoevaluacion->getEvaluacionId() ?></td>
</tr>
<tr>
<th>Activo: </th>
<td><?php echo $grupoevaluacion->getActivo() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $grupoevaluacion->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'grupoevaluacion/edit?id='.$grupoevaluacion->getId()) ?>
&nbsp;<?php echo link_to('list', 'grupoevaluacion/list') ?>
