default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gestión de alumnos
    robots:       nofollow
    description:  Gestión de alumnos
    keywords:     symfony, project
    language:     es

  stylesheets:    [estilos, menu, menu_secundario, listado, mostrar, admin, editar, horario, calendario ]

  javascripts:    []

  has_layout:     on
  layout:         layout
