<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Listado de festivos') ?></h1>
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Id') ?></th>
  <th><?php echo __('Evaluacion') ?></th>
  <th><?php echo __('Fecha') ?></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($festivos as $festivo):
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>
<tr class="<?php echo $fila ?>">
    <td><?php echo link_to($festivo->getId(), 'festivo/show?id='.$festivo->getId()) ?></td>
      <td><?php
       foreach ($evaluaciones as $evaluacion):
       if ($evaluacion->getId() == $festivo->getEvaluacionId())
       {
         echo $evaluacion->getTitulo();
       }
       endforeach;
      ?></td>
      <td><?php 
       //Obtenemos el formato para las fechas 
   if ($sf_user->getCulture() == 'es')
   {
      $formato = 'd/m/Y';   
   } 
   if ($sf_user->getCulture() == 'eu')
   {
      $formato = 'Y/m/d';   
   }  
   
   echo date($formato,strtotime($festivo->getFecha()))
   ?></td>
  </tr>
<?php
$x++; 
endforeach; ?>
</tbody>
</table>

<div id="linea"></div>	
<div class="exit">
<?php echo link_to (__('Volver'), 'festivo/index?fecha='.$fecha[0]) ?>
</div>
</div>
</div>
