<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Editar evaluación') ?></h1>
</div>
<div id="editar">

<?php use_helper('Object') ?>

<?php echo form_tag('evaluacion/update', 'name=formulario') ?>

<?php echo object_input_hidden_tag($evaluacion, 'getId') ?>

<?php echo object_input_hidden_tag($evaluacion, 'getActivo', array (
  'value' => true
  )); ?>

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos evaluación') ?></th>
</tr>
</thead>
<tbody>
<tr>
  <td class="nombres"><label><?php echo __('Titulo') ?>: </label></td><td><?php echo input_tag('titulo_ev', $evaluacion->getTitulo(), array (
  'size' => 50,
)) ?></td>
</tr>
<tr>
<td class="nombres"><label><?php echo __('Fecha inicio') ?>: </label></td>
 <td><?php 
  if ($sf_user->getCulture() == 'es')
  {  
  echo object_input_date_tag($evaluacion, 'getFechaini', array (
  'rich' => true,
  'value' => format_date($evaluacion->getFechaini())
));
  }
  if ($sf_user->getCulture() == 'eu')
  {
  echo object_input_date_tag($evaluacion, 'getFechaini', array (
  'rich' => true,
  'value' => format_date($evaluacion->getFechaini())
));
  }
  ?></td>
</tr>
<tr>
<td class="nombres"><label><?php echo __('Fecha fin') ?>: </label></td><td><?php 
  if ($sf_user->getCulture() == 'es')
  {  
  echo object_input_date_tag($evaluacion, 'getFechafin', array (
  'rich' => true,
  'value' => format_date($evaluacion->getFechafin())
));
  }
  if ($sf_user->getCulture() == 'eu')
  {
  echo object_input_date_tag($evaluacion, 'getFechafin', array (
  'rich' => true,
  'value' => format_date($evaluacion->getFechafin())
));
  }
  ?></td>
</tr>
<tr>
  <td class="nombres"><label><?php echo __('Observaciones') ?>: </label></td><td><?php echo object_textarea_tag($evaluacion, 'getObservaciones', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>

<div id="linea"></div>	
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<?php if ($evaluacion->getId()): ?>
   <div class="delete"><?php echo link_to(__('Eliminar'), 'evaluacion/delete?id='.$evaluacion->getId(), 'post=true&confirm='.__('Are you sure?')) ?></div>
   <div class="cancel"><?php echo link_to(__('Cancelar'), 'evaluacion/show?id='.$evaluacion->getId()) ?></div>
<?php else: ?>
   <div class="cancel"><?php echo link_to(__('Cancelar'), 'evaluacion/list') ?></div>
<?php endif; ?>
</form>
</div>
</div>