<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Javascript') ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas de los alumnos') ?> <?php echo $grupo->getNombre()?></h1>
</div>
  <div id="listado">
  <table cellspacing="0">
  <thead>
  <tr>
    <th><?php echo __('Alumno') ?></th>
    <th><?php echo __('Evaluación') ?></th>
    <th><?php echo __('Faltas') ?></th>
  </tr>
  </thead>
  <tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno):
foreach ($evaluaciones as $evaluacion):?> 
<?php 
 if ($x%2 == 0)
  {
    $fila = "p";
  }
  else    
  {
    $fila = "i";
  }?>  
<tr class="<?php echo $fila ?>">
<td><?php 
 if ($evaluacion->getId() == 1)
 {
 echo $alumno->getNombre();
 }
 else
 {
  echo "&nbsp;"; 
 }?>  
</td> 
<td><?php echo $evaluacion->getTitulo()?></td>
<td><?php echo link_to(__('Ver faltas'), 'falta/alalumnolistfaltas?alumno='.$alumno->getId().'&grupo='.$grupo->getId().'&evaluacion='.$evaluacion->getId().'&fecha='.$fecha); ?>
</td>
</tr>
<?php
endforeach;
$x++;
?>
<?php
endforeach;?> 
</tbody>
</table>
</div>
<div id="linea"></div>
<div class="exit">
<?php 
echo link_to(__('Volver'), 'falta/algrupolist?fecha='.$fecha); 
?>
</div>	
</div>


