<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Editar falta') ?></h1>
</div>
<div id="editar">

<?php use_helper('Object') ?>

<?php echo form_tag('falta/update', 'name=formulario') ?>

<?php echo object_input_hidden_tag($falta, 'getId') ?>
<?php echo object_input_hidden_tag($falta, 'getAlumnoId', array (
  'value' => $alumno->getId()
  )) ?>
<?php echo object_input_hidden_tag($falta, 'getDia', array (
  'value' => $dia
  )) ?>
<?php echo object_input_hidden_tag($falta, 'getHora', array (
  'value' => $hora
  )) ?>
  
  <?php echo object_input_hidden_tag($falta, 'getAsignaturaId', array (
  'value' => $asignatura
  )) ?>
  
   <?php echo object_input_hidden_tag($falta, 'getFecha', array (
  'value' => $fecha
  )) ?>
  
     <?php echo object_input_hidden_tag($falta, 'getEvaluacionId', array (
  'value' => $evaluacion->getId()
  )) ?>

<?php echo object_input_hidden_tag($falta, 'getActivo', array (
  'value' => true
  ));   
  ?>
<?php echo input_hidden_tag('crear', $crear) ?>
  
<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th><?php echo __('Datos falta') ?></th>
</tr>
</thead>
<tbody>
<tr>

  <td class="nombres"><label><?php echo __('Evaluacion') ?>: </label></td><td>
  <?php echo $evaluacion->getTitulo()?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Alumno') ?>: </label></td><td><?php echo $alumno->getNombre() ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Asignatura') ?>: </label></td><td><?php echo $asig->getNombre() ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Dia') ?>: </label></td><td><?php 
      include_component('principal','dias',array(
      'dia' => $dia
      ));
     ?>
  
   </td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Hora') ?>: </label></td><td><?php 
      include_component('principal','horas',array(
      'hora' => $hora
      ));
     ?></td>
</tr>
<tr>
  <?php if ($falta->getFecha() == "")
  {?>
  <td class="nombres"><label><?php echo __('Fecha') ?>: </label></td><td><?php 
  if ($sf_user->getCulture() == 'es')
  {  
  echo date('d/m/Y',strtotime($fecha)); 
 }
 if ($sf_user->getCulture() == 'eu')
  {  
  echo date('Y/m/d',strtotime($fecha)); 
 }?></td>
  <?php 
  }
  else
  {?>
    <td class="nombres"><label><?php echo __('Fecha') ?>: </label></td><td><?php 
    if ($sf_user->getCulture() == 'es')
    {  
     echo date('d-m-Y',strtotime($falta->getFecha())); 
    }
    if ($sf_user->getCulture() == 'eu')
    {  
     echo date('Y-m-d',strtotime($falta->getFecha())); 
    }?>
 </td>
  <?php 
 }?> 
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Justificado') ?>: </label></td><td><?php echo object_checkbox_tag($falta, 'getJustificado', array (
)) ?></td>
</tr>
<tr>

  <td class="nombres"><label><?php echo __('Observaciones') ?>: </label></td><td><?php echo object_textarea_tag($falta, 'getObservaciones', array (
  'size' => '30x3',
)) ?></td>
</tr>
</tbody>
</table>

<div id="linea"></div>	
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<?php if ($falta->getId()): ?>
  <div class="delete"><?php echo link_to(__('Eliminar'), 'falta/delete?id='.$falta->getId().'&fecha='.strtotime($fecha), 'post=true&confirm='.__('Are you sure?')) ?></div>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'falta/show?id='.$falta->getId().'grupo='.$alumno->getGrupoId().'&dia='.$dia.'&hora='.$hora.'&asignatura='.$asignatura.'&fecha='.strtotime($fecha)) ?></div>
<?php else: ?>
  <div class="cancel"><?php echo link_to(__('Cancelar'), 'falta/list?grupo='.$alumno->getGrupoId().'&dia='.$dia.'&hora='.$hora.'&asignatura='.$asignatura.'&fecha='.strtotime($fecha)) ?></div>
<?php endif; ?>
</form>
</div>
</div>