<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas por alumno entre fechas') ?></h1>
</div>
<div id="listado">
<?php use_helper('Object') ?>
<?php 
echo form_tag('falta/fechasalumnolistado', 'name=formulario');
?>
<?php echo input_hidden_tag('fecha', $fecha);?>

<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Listado por alumno') ?></th>
  <th></th>
  <th></th>
  <th></th>
</tr>
</thead>
<tbody>
<tr class="i" style="height: 40px;">
  <td><?php echo __('Escoge alumno') ?> <?php echo select_tag('alumno_id', objects_for_select(
  AlumnoPeer::doSelect($c),
  'getId',
  'getNombre',
  0
 ))?>
 </td>
 <td><?php echo __('Escoge fecha inicial') ?> <?php 
  $d = strtotime("now");
  $d=$d-(3600*24*30); 
  echo input_date_tag('fecha_ini', format_date(date('d/m/Y',$d),'d') , 'rich=true');
  ?>
 </td>
 <td><?php echo __('Escoge fecha final') ?> <?php  
 $d = strtotime("now");
 
  echo input_date_tag('fecha_fin', format_date(date('d/m/Y',$d),'d') , 'rich=true'); 
  ?>
 </td>  
 <td>
 <div> 
<?php 
//echo link_to_function(__('Listado'), "enviar()"); 
echo submit_to_remote ('Enviar',__('Listado'),array(
  'update' => 'listado1',
  'url' => 'falta/fechasalumnolistado'
  )); 
?> 
</div>
</td>
</tr>
</tbody>
</table>
<hr />
</form>

<div id="listado1">

</div>

<div id="linea"></div>
<div class="exit">
<?php 
echo link_to(__('Volver'), 'falta/fechasgrupolist?fecha='.$fecha); 
?>
</div>	
</div>



