<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Horario de') ?> <?php echo $sf_user->getAttribute('nombre'); ?></h1>
</div>
<div id="horario">
<table cellspacing="0">
<thead>
<tr>
  <th style="text-align: left; padding-left: 5px;"><?php echo link_to(image_tag('/images/iconos/date_previous.png'),'falta/index?fecha='.strtotime("-1 month",$fecha[0]))?> </th>
  <th colspan="5"><?php include_component('principal','meses',array(
     'mes' => $fecha['mon'] 
     ));?></th>
  <th style="text-align: right;width: 12px;padding-right: 5px;"><?php echo link_to(image_tag('/images/iconos/date_next.png'),'falta/index?fecha='.strtotime("+1 month",$fecha[0]))?></th>
</tr>
<tr>
  <th style="text-align: left; padding-left: 5px;"><?php echo link_to(image_tag('/images/iconos/date_previous.png'),'falta/index?fecha='.strtotime("-7 day",$fecha[0]))?></th>
  <th><?php echo __('Lunes') ?></th>
  <th><?php echo __('Martes') ?></th>
  <th><?php echo __('Miércoles') ?></th>
  <th><?php echo __('Jueves') ?></th>
  <th><?php echo __('Viernes') ?></th>
  <th style="text-align: right;width: 12px;padding-right: 5px;"><?php echo link_to(image_tag('/images/iconos/date_next.png'),'falta/index?fecha='.strtotime("+7 day",$fecha[0]))?></th>
</tr>
<tr>
  <?php 
   $dia = $fecha['wday'];
   switch ($dia)
   {   
      case 1:
        $lunes = $fecha[0];
        $martes = strtotime("+1 day",$fecha[0]);
        $miercoles = strtotime("+2 day",$fecha[0]);
        $jueves = strtotime("+3 day",$fecha[0]);
        $viernes = strtotime("+4 day",$fecha[0]);
        break;
      case 2:
        $lunes = strtotime("-1 day",$fecha[0]);
        $martes = $fecha[0];
        $miercoles = strtotime("+1 day",$fecha[0]);
        $jueves = strtotime("+2 day",$fecha[0]);
        $viernes = strtotime("+3 day",$fecha[0]);
        break;
      case 3:
        $lunes = strtotime("-2 day",$fecha[0]);
        $martes = strtotime("-1 day",$fecha[0]);
        $miercoles = $fecha[0];
        $jueves = strtotime("+1 day",$fecha[0]);
        $viernes = strtotime("+2 day",$fecha[0]);
        break;
      case 4:
        $lunes = strtotime("-3 day",$fecha[0]);
        $martes = strtotime("-2 day",$fecha[0]);
        $miercoles = strtotime("-1 day",$fecha[0]);
        $jueves = $fecha[0];
        $viernes = strtotime("+1 day",$fecha[0]);
        break;
      case 5:
        $lunes = strtotime("-4 day",$fecha[0]);
        $martes = strtotime("-3 day",$fecha[0]);
        $miercoles = strtotime("-2 day",$fecha[0]);
        $jueves = strtotime("-1 day",$fecha[0]);
        $viernes = $fecha[0];
        break;
      case 6:
        $lunes = strtotime("-5 day",$fecha[0]);
        $martes = strtotime("-4 day",$fecha[0]);
        $miercoles = strtotime("-3 day",$fecha[0]);
        $jueves = strtotime("-2 day",$fecha[0]);
        $viernes = strtotime("-1 day",$fecha[0]);
        break;
      case 0: 
        $lunes = strtotime("-6 day",$fecha[0]);
        $martes = strtotime("-5 day",$fecha[0]);
        $miercoles = strtotime("-4 day",$fecha[0]);
        $jueves = strtotime("-3 day",$fecha[0]);
        $viernes = strtotime("-2 day",$fecha[0]);
        break;   
   }  
  ?>  
  <th><?php echo __('Horas') ?></th>
  <?php 
   if ($sf_user->getCulture() == 'es')
   { 
      $formato = 'd/m/Y';   
   } 
   if ($sf_user->getCulture() == 'eu')
   {
      $formato = 'Y/m/d';   
   }  
  
  //Miramos si algún día de la semana es festivo
  $lunes_fest = false;
  $martes_fest = false;
  $miercoles_fest = false;
  $jueves_fest = false;
  $viernes_fest = false; 
  foreach ($festivos as $festivo):
    if ($festivo->getFecha() == date('Y-m-d',$lunes))
    {
      $lunes_fest = true;
    }
    if ($festivo->getFecha() == date('Y-m-d',$martes))
    {
      $martes_fest = true;
    }
    if ($festivo->getFecha() == date('Y-m-d',$miercoles)) 
    {
      $miercoles_fest = true;
    }
    if ($festivo->getFecha() == date('Y-m-d',$jueves))
    {
      $jueves_fest = true;
    }
    if ($festivo->getFecha() == date('Y-m-d',$viernes)) 
    {
      $viernes_fest = true;
    }
  endforeach;  
  ?>
  <th><?php echo link_to(date($formato,$lunes),'falta/tabla?fecha='.$lunes.'&dia=1'); ?></th>
  <th><?php echo link_to(date($formato,$martes),'falta/tabla?fecha='.$martes.'&dia=2'); ?></th>
  <th><?php echo link_to(date($formato,$miercoles),'falta/tabla?fecha='.$miercoles.'&dia=3');?></th>
  <th><?php echo link_to(date($formato,$jueves),'falta/tabla?fecha='.$jueves.'&dia=4'); ?></th>
  <th><?php echo link_to(date($formato,$viernes),'falta/tabla?fecha='.$viernes.'&dia=5'); ?></th>
  <th style="width: 12px;">&nbsp;</th>
</tr>
</thead>
<tbody>
<?php
$y = 0;
$hora = 0;
$primera = "i";
$segunda = "p";
$rojo = "f";
for($hora;$hora<count($horas);$hora++)
{
 //if ($hora % 2 ==0)
 //{
 //  $x = $primera;
 //  $primera = $segunda;
 //  $segunda = $x;
 //}
?>
<?php $y++; ?>
<tr>
    <th class="<?php
    if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
    ?>">
    <?php include_component('principal','horas',array(
     'hora' => $hora
     ));  
      
     ?> 
      </th> 
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>">
      <?php
      foreach ($horarios as $horario):
        if ($horario->getDia() == 1 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          if ($lunes_fest == false) 
          {
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'falta/tablafaltas?grupo='.$horario->getGrupoId().'&dia='.$horario->getDia().'&hora='.$horario->getHora().'&asignatura='.$asig_id.'&fecha='.$lunes); 
          }
          else
          {
            echo __('FESTIVO'); 
          }
        }
      endforeach;  
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>">
      <?php
      foreach ($horarios as $horario):
        if ($horario->getDia() == 2 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          if ($martes_fest == false)
          {
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'falta/tablafaltas?grupo='.$horario->getGrupoId().'&dia='.$horario->getDia().'&hora='.$horario->getHora().'&asignatura='.$asig_id.'&fecha='.$martes); 
          }
          else
          {
            echo __('FESTIVO'); 
          }
        }
      endforeach;
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>">
      <?php
      foreach ($horarios as $horario):
        if ($horario->getDia() == 3 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          if ($miercoles_fest == false)
          {
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'falta/tablafaltas?grupo='.$horario->getGrupoId().'&dia='.$horario->getDia().'&hora='.$horario->getHora().'&asignatura='.$asig_id.'&fecha='.$miercoles); 
          }
          else
          {
            echo __('FESTIVO'); 
          }
 
        }
      endforeach;
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>">
      <?php
      foreach ($horarios as $horario):
        if ($horario->getDia() == 4 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          if ($jueves_fest == false)
          {
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'falta/tablafaltas?grupo='.$horario->getGrupoId().'&dia='.$horario->getDia().'&hora='.$horario->getHora().'&asignatura='.$asig_id.'&fecha='.$jueves); 
          }
          else
          {
            echo __('FESTIVO'); 
          }

        }
      endforeach;
      ?></td>
      <td class="<?php
      if ($y % 2 == 1)
      {
        echo $primera;
      }
      else
      {
        echo $segunda;
      }
      ?>">
      <?php
      foreach ($horarios as $horario):
        if ($horario->getDia() == 5 && $horario->getHora()==$hora)
        { 
          foreach ($asignaturas as $asignatura):
            if ($horario->getAsignaturaId() == $asignatura->getId())
            {
              $asig_nombre = $asignatura->getNombre();
              $asig_id = $asignatura->getId();            
            }
          endforeach;
          
          foreach ($grupos as $grupo):
            if ($horario->getGrupoId() == $grupo->getId())
            {
              $grupo_nombre = $grupo->getNombre();
              $grupo_id = $grupo->getId();            
            }
          endforeach;
          if ($viernes_fest == false)
          {
          echo link_to($asig_nombre. "<br />". $grupo_nombre, 'falta/tablafaltas?grupo='.$horario->getGrupoId().'&dia='.$horario->getDia().'&hora='.$horario->getHora().'&asignatura='.$asig_id.'&fecha='.$viernes); 
          }
          else
          {
            echo __('FESTIVO'); 
          }

        }
      endforeach;
      ?></td>
      <th style="width: 12px;">&nbsp;</th>
  </tr>
<?php
//if ($hora % 2 ==0)
// {
//   $x = $primera;
//   $primera = $segunda;
//   $segunda = $x;
// }
}?>
</tbody>
</table>


<div id="linea"></div>
<div class="list">
<?php echo link_to (__('Listado de faltas de grupo por alumno y evaluación'), 'falta/totalgrupolist?fecha='.$fecha[0]) ?>
</div>
<!--<div class="list">
<?php 
//echo link_to (__('Listado por alumno entre fechas'), 'falta/fechasgrupolist?fecha='.$fecha[0]);
?>
</div>-->
<div class="list">
<?php echo link_to (__('Listado por alumno y asignatura'), 'falta/asiggrupolist?fecha='.$fecha[0]) ?>
</div>
<div class="list">
<?php echo link_to (__('Listado de faltas de grupo por alumno y asignatura'), 'falta/totalasiggrupolist?fecha='.$fecha[0]) ?>
</div>
<div id="linea"></div>
<div class="list">
<?php echo link_to (__('Listado detallado de faltas (imprimir)'), 'falta/grupolist?fecha='.$fecha[0]) ?>
</div>
<div class="list">
<?php echo link_to (__('Listado detallado de faltas por evaluacion (imprimir)'), 'falta/grupolisteval?fecha='.$fecha[0]) ?>
</div>
<div class="list">
<?php echo link_to (__('Listado anual de faltas'), 'falta/recgrupolist?fecha='.$fecha[0]) ?>
</div>
<div class="list">
<?php echo link_to (__('Listado de faltas por alumno y evaluación'), 'falta/algrupolist?fecha='.$fecha[0]) ?>
</div>
<!--<div class="list">-->
<?php 
//echo link_to($asig_nombre. "<br />". $grupo_nombre, 'falta/list?grupo='.$horario->getGrupoId().'&dia='.$horario->getDia().'&hora='.$horario->getHora().'&asignatura='.$asig_id.'&fecha='.$lunes); 
?>
<!--</div>-->
</div>
</div>

