<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas de alumnos') ?></h1>
</div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Alumno') ?></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
  <th></th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>

<tr class="<?php echo $fila ?>">
   <td><?php echo $alumno->getNombre() ?></td>
   <td>|</td>
   <td><?php echo link_to (__('Crear falta'), 'falta/create?alumno='.$alumno->getId().'&dia='.$dia.'&hora='.$hora.'&asignatura='.$asignatura.'&fecha='.$fecha) ?></td>
   <td>|</td>
   <td><?php 
      echo include_component ('principal','dias', array (
      'dia' => $dia
      )); 
      echo include_component ('principal','horas', array ( 
      'hora' => $hora 
      ));
      echo $asig->getNombre();
      echo link_to(__(' Ver faltas'), 'falta/faltas?alumno='.$alumno->getId().'&dia='.$dia.'&hora='.$hora.'&asignatura='.$asignatura.'&fecha='.$fecha) ?></td>
   <td>|</td>   
   <td><?php echo link_to(__('Listado total de faltas'), 'falta/total?alumno='.$alumno->getId().'&dia='.$dia.'&hora='.$hora.'&asignatura='.$asignatura.'&fecha='.$fecha) ?></td>
</tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>

<div id="linea"></div>
<div class="exit">
<?php echo link_to (__('Volver'), 'falta/index?fecha='.$fecha) ?>
</div>	
</div>
</div>
