<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Visualizar falta') ?></h1>
</div>
<div id="mostrar">

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th id="sf_admin_list_th_id"><?php echo __('Datos falta') ?></th>
</tr>
</thead>
<tbody>
<tr>
<th><?php echo __('Id') ?>: </th>
<td class="i"><?php echo $falta->getId() ?></td>
</tr>
<tr>
<th><?php echo __('Evaluacion') ?>: </th>
<td class="p">
<?php 
  foreach ($evaluaciones as $evaluacion):
   if ($evaluacion->getId() == $falta->getEvaluacionId())
   {
      echo $evaluacion->getTitulo();   
   }  
  endforeach;?></td>
</tr>
<tr>
<th><?php echo __('Alumno') ?>: </th>
<td class="i"><?php echo $alumno->getNombre() ?></td>
</tr>
<tr>
<th><?php echo __('Asignatura') ?>: </th>
<td class="p"><?php echo $asig->getNombre() ?></td>
</tr>
<tr>
<th><?php echo __('Dia') ?>: </th>
<td class="i"><?php 
      include_component ('principal','dias', array (
      'dia' => $falta->getDia() 
      ));?></td>
</tr>
<tr>
<th><?php echo __('Hora') ?>: </th>
<td class="p"><?php 
      include_component ('principal','horas', array (
      'hora' => $falta->getHora() 
      ));?></td>
</tr>
<tr>
<th><?php echo __('Fecha') ?>: </th>
<td class="i"><?php 
    if ($sf_user->getCulture() == 'es')
    {  
     echo date('d-m-Y',strtotime($falta->getFecha())); 
    }
    if ($sf_user->getCulture() == 'eu')
    {  
     echo date('Y-m-d',strtotime($falta->getFecha())); 
    }?></td>
</tr>
<tr>
<th><?php echo __('Justificado') ?>: </th>
<td class="i"><?php 
if ($falta->getJustificado())
{
  echo __('SI');
}
else
{
  echo __('NO');
} ?></td>
</tr>
<tr>
<th><?php echo __('Observaciones') ?>: </th>
<td class="p"><?php echo $falta->getObservaciones() ?></td>
</tr>
<tr>
<th><?php echo __('Actualizado') ?>: </th>
<td class="i"><?php echo $falta->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>

<div id="linea"></div>	
<div class="edit">
<?php echo link_to(__('Editar'), 'falta/edit?id='.$falta->getId().'&fecha='.strtotime($falta->getFecha())) ?>
</div>
<div class="list">
<?php echo link_to(__('Listado'), 'falta/list?grupo='.$alumno->getGrupoId().'&dia='.$dia.'&hora='.$hora.'&asignatura='.$asignatura.'&fecha='.strtotime($falta->getFecha())) ?>
</div>
</div>
</div>