<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>

<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<?php
foreach ($alumnos as $alumno):
    $var = "im".$alumno->getId();
    echo javascript_tag("
    function imagen".$alumno->getId()."(ver) {
       document.getElementById('".$var."').style.visibility = ver;
       }
        ");
endforeach;
?>

<?php echo form_tag('falta/salvar', 'name = formulario' ) ?>

<?php echo input_hidden_tag('grupo', $grupo) ?>
<?php echo input_hidden_tag('dia', $dia) ?>
<?php echo input_hidden_tag('hora', $hora) ?>
<?php echo input_hidden_tag('asignatura', $asig->getId()) ?>
<?php echo input_hidden_tag('evaluacion', $evaluacion->getId()) ?>
<?php echo input_hidden_tag('fecha', strtotime($fecha)) ?>

<div id="contenedor">
<div id="titulo">
    <h1><?php 
    echo __('Faltas de alumnos').' ('.$asig->getNombre().' '.date('d/m/Y',strtotime($fecha)).' ';
    include_component('principal','horas',array(
     'hora' => $hora
     ));
     echo ')'; ?></h1>
</div>

<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Alumno') ?></th>
  <th>Falta</th>
  <th>Retraso</th>
  <th>Justificado</th>
  <th>Observaciones</th>
  <th>&nbsp;</th>
</tr>
</thead>
<tbody>
<?php 
$x=1;
foreach ($alumnos as $alumno): 
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>

<tr class="<?php echo $fila ?>" id="<?php echo $alumno->getId()?>">
   <?php
   $vis = "imagen".$alumno->getId()."('visible')";
   $oc = "imagen".$alumno->getId()."('hidden')";
   ?>
   <td><img src="/images/iconos/camera_small.png" onmouseover="<?php echo $vis; ?>" onmouseout="<?php echo $oc; ?>" /><?php echo $alumno->getNombre() ?>
       <div id="im<?php echo $alumno->getId();?>" style="visibility:hidden;position:absolute;">
           <?php $ruta="/images/grupos/".$alumno->getGrupoId()."/".$alumno->getId().".jpg";?>
           <img src="<?php echo $ruta?>" style="width:100px;" />
       </div>
   </td>
   <td><?php 
   $encontrado = false;
   foreach ($faltas as $falta):
     if ($falta->getAlumnoId() == $alumno->getId())
     {
       echo radiobutton_tag('falta'.$alumno->getId(), 1 , true);
       echo "</td>";
       echo "<td>";
       echo radiobutton_tag('falta'.$alumno->getId(), 2 , false);
       $encontrado = true;
     }  
   endforeach;
   if ($encontrado == false)
   {
     foreach ($retrasos as $retraso):
       if ($retraso->getAlumnoId() == $alumno->getId())
       {
         echo radiobutton_tag('falta'.$alumno->getId(), 1 , false);
         echo "</td>";
         echo "<td>";
         echo radiobutton_tag('falta'.$alumno->getId(), 2 , true);
         $encontrado = true;
       }
     endforeach;
   }
   
   if ($encontrado == false)
   {
     echo radiobutton_tag('falta'.$alumno->getId(), 1 , false);
     echo "</td>";
     echo "<td>";
     echo radiobutton_tag('falta'.$alumno->getId(), 2 , false);
   }
   ?></td>
   <td><?php 
   $encontrado = false; 
   foreach ($faltas as $falta):
     if ($falta->getAlumnoId() == $alumno->getId())
     { 
        echo checkbox_tag('justificado'.$alumno->getId(), true, $falta->getJustificado());
        echo "</td>"; 
        echo "<td>";
        echo textarea_tag('observaciones'.$alumno->getId(),$falta->getObservaciones(), 'size=20x1');
        $encontrado = true;
     }
   endforeach; 
   if ($encontrado == false)
   {
     foreach ($retrasos as $retraso):
       if ($retraso->getAlumnoId() == $alumno->getId())
       { 
         echo checkbox_tag('justificado'.$alumno->getId(), true, $retraso->getJustificado());
         echo "</td>"; 
         echo "<td>";
         echo textarea_tag('observaciones'.$alumno->getId(),$retraso->getObservaciones(), 'size=20x1');
         $encontrado = true;
       }
     endforeach; 
   }
   if ($encontrado == false)
   {
     echo checkbox_tag('justificado'.$alumno->getId(), true, false);
     echo "</td>"; 
     echo "<td>";
     echo textarea_tag('observaciones'.$alumno->getId(), '', 'size=20x1'); 
   }
   ?></td>
   <td>
   <div class="cancel"> 
   <?php echo 
   link_to_remote('Limpiar', array(
     'update' => $alumno->getId(),
     'url' => 'falta/limpiar?id='.$alumno->getId()
     ))?>
   </div>
   </td>
</tr>
<?php 
$x++;
endforeach; ?>
</tbody>
</table>
</form>

<div id="linea"></div>
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<div class="exit"> 
<?php echo link_to (__('Volver'), 'falta/index?fecha='.strtotime($fecha)) ?>
</div>	

</div>
</div>
