<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
") ?>

<?php echo javascript_tag("
  function enviar1()
  {
   document.formulario1.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas de alumnos') ?></h1>
</div>
<div id="listado">
<?php use_helper('Object') ?>

<table cellspacing="0">
<thead>
<tr>
  <th colspan="2"><?php echo __('Tabla de faltas por grupo y día') ?></th>
</tr>
</thead>
<tbody>
<?php
if ($grupos)
{?>
<?php echo form_tag('falta/tablalist', 'name=formulario') ?>
<?php echo input_hidden_tag('fecha', $fecha);?>
<?php echo input_hidden_tag('dia', $dia);?>
<?php echo input_hidden_tag('tutor', false);?>

<tr class="i">
  <td style="width: 150px; height: 40px;"><?php echo __('Escoge grupo') ?> <?php echo select_tag('grupo', objects_for_select(
  GrupoPeer::doSelect($c),
  'getId',
  'getNombre',
  0
 ))?>
 </td>
 <td>
 <div class="list_alum">
<?php echo link_to_function(__('Aceptar'), "enviar()"); ?>
</div>
</td>
</tr>
</form>
<?php
}
?>

<?php echo form_tag('falta/tablalist', 'name=formulario1') ?>
<?php echo input_hidden_tag('fecha', $fecha);?>
<?php echo input_hidden_tag('dia', $dia);?>
<?php echo input_hidden_tag('grupo', $grupo->getId());?>
<?php echo input_hidden_tag('tutor', true);?>

<?php
if ($grupos)
{?>
<tr class="p">
<?php
}
else
{
?>
  <tr class="i">
<?php
}
?>

  <td style="width: 150px; height: 40px;"><?php
  echo __('Grupo tutor');
  echo " ";
  echo $grupo->getNombre();?>
 </td>
 <td>
 <div class="list_alum">
<?php echo link_to_function(__('Aceptar'), "enviar1()"); ?>
</div>
</td>
</tr>
</form>

</tbody>
</table>
<hr />
<div id="linea"></div>
<div class="exit">
<?php 
echo link_to(__('Volver'), 'falta/index?fecha='.$fecha); 
?>
</div>	
</div>
</div>


