<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>
<?php echo javascript_tag("
  function enviar1()
  {
   document.formulario1.submit();
  }
") ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas de alumnos por evaluación') ?></h1>
</div>
<div id="listado">
<?php use_helper('Object') ?>

<?php echo form_tag('falta/alumnolisteval', 'name=formulario1') ?>
<table cellspacing="0">
<thead>
<tr>
  <th colspan="2"><?php echo __('Faltas de alumnos por evaluación') ?></th>
</tr>
</thead>
<tbody>
<tr class="i">
  <td style="width: 40%;height: 40px;"><?php echo __('Escoge grupo') ?> <?php echo select_tag('grupo_id', objects_for_select(
  GrupoPeer::doSelect($c),
  'getId',
  'getNombre',
  0
 ));
  echo "&nbsp;";
  echo submit_to_remote('Aceptar',__('Aceptar'),array(
   'update' => 'grupoev',
   'url' => 'falta/grupoev'
 ));
 ?>
 </td>
 
<td style="width: 40%;height: 40px;" id="grupoev">
      
</td>
</tr>
</tbody>
</table>
</form>
</div>




