<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<?php use_helper('Object') ?>
<?php use_helper('Javascript') ?>

<?php echo javascript_tag("
  function enviar()
  {
   document.formulario.submit();
  }
  function imagen(ver) {
  document.getElementById('im').style.visibility = ver;
}
") ?>
<?php
foreach ($alumnos as $alumno):
    $var = "im".$alumno->getId();
    echo javascript_tag("
    function imagen".$alumno->getId()."(ver) {
       document.getElementById('".$var."').style.visibility = ver;
       }
        ");
endforeach;
?>

<?php echo form_tag('falta/salvartodo', 'name = formulario' ) ?>

<?php echo input_hidden_tag('grupo', $grupo) ?>
<?php echo input_hidden_tag('dia', $dia) ?>
<?php echo input_hidden_tag('evaluacion', $evaluacion->getId()) ?>
<?php echo input_hidden_tag('fecha', strtotime($fecha)) ?>

<div id="contenedor">
<div id="titulo">
    <h1><?php 
    echo __('Faltas de alumnos').' ('.date('d/m/Y',strtotime($fecha)).')';?>
    </h1>
</div>

<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th>Asignaturas</th>
  <?php
  foreach ($horarios as $horario):
      foreach ($asignaturas as $asignatura):
          if ($asignatura->getId() == $horario->getAsignaturaId())
          {
             echo "<th colspan='3' style='text-align: center; border-left: 1px solid black;'>";
             echo $asignatura->getNombre();
             echo "<br />";
             include_component('principal','horas',array(
              'hora' => $horario->getHora(),
              'profesor' => $horario->getProfesorId()
               ));
             echo "</th>";
          }
      endforeach;
      
  endforeach;
  ?>
</tr>
<tr>
    <th style="background-color: #ddd;"><?php echo __('Alumno') ?></th>
    <?php
    foreach ($horarios as $horario):
      foreach ($asignaturas as $asignatura):
          if ($asignatura->getId() == $horario->getAsignaturaId())
          {
             echo "<th style='background-color: #ddd;border-left: 1px solid black;'>&nbsp;F&nbsp;&nbsp;&nbsp;&nbsp;R</th>";
             echo "<th style='background-color: #ddd;'>J</th>";
             echo "<th style='background-color: #ddd;'></th>";
          }
      endforeach;
  endforeach;
  ?>
</tr>
</thead>
<tbody>
<?php
$x=1;
foreach ($alumnos as $alumno):
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
?>

<tr class="<?php echo $fila ?>">
   <?php
   $vis = "imagen".$alumno->getId()."('visible')";
   $oc = "imagen".$alumno->getId()."('hidden')";
   ?>
   <td><img src="/itutor/images/iconos/camera_small.png" onmouseover="<?php echo $vis; ?>" onmouseout="<?php echo $oc; ?>" /><?php echo $alumno->getNombre() ?>
       <div id="im<?php echo $alumno->getId();?>" style="visibility:hidden;position:absolute;">
           <?php $ruta="/itutor/images/grupos/".$alumno->getGrupoId()."/".$alumno->getId().".jpg";?>
           <img src="<?php echo $ruta?>" style="width:100px;" />
       </div>
   </td>
   <?php
   foreach ($horarios as $horario):
       echo "<td style='border-left: 1px solid black;' id ='alum".$alumno->getId().$horario->getHora()."'>";
       $f = false;
       $r = false;
       $justificado = false;
       foreach ($faltas as $falta):
           if ($falta->getAlumnoId() == $alumno->getId() && $falta->getAsignaturaId() == $horario->getAsignaturaId() && $horario->getHora() == $falta->getHora() && $dia == $falta->getDia() && $fecha == $falta->getFecha())
           {
             $f = true;
             $justificado = $falta->getJustificado();
           }
       endforeach;
       foreach ($retrasos as $retraso):
           if ($retraso->getAlumnoId() == $alumno->getId() && $retraso->getAsignaturaId() == $horario->getAsignaturaId() && $horario->getHora() == $retraso->getHora() && $dia == $retraso->getDia() && $fecha == $retraso->getFecha())
           {
             $r = true;
             $justificado = $retraso->getJustificado();
           }
       endforeach;
       echo radiobutton_tag('f'.$alumno->getId().$horario->getHora(),'f',$f);
       echo "&nbsp;";
       echo "&nbsp;";
       echo radiobutton_tag('f'.$alumno->getId().$horario->getHora(),'r',$r);
       echo "</td><td>";
       echo checkbox_tag('j'.$alumno->getId().$horario->getHora(), 1, $justificado);
       echo "</td>";
       echo "</td><td>";
       echo link_to_remote(image_tag('/images/iconos/delete1.png'), array(
       'update' => 'alum'.$alumno->getId().$horario->getHora(),
       'url' => 'falta/limp?id='.$alumno->getId().'&hora='.$horario->getHora()
      ));
       echo "</td>";
   endforeach;
   ?>
</tr>
<?php
$x++;
endforeach; ?>
</tbody>
</table>
</form>
<div id="linea"></div>
<div class="save">
<?php echo link_to_function(__('Guardar'), "enviar()"); ?>
</div>
<div class="exit"> 
<?php echo link_to (__('Volver'), 'falta/index?fecha='.strtotime($fecha)) ?>
</div>	

</div>
</div>
