<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas totales del grupo') ?> <?php echo $grupo->getNombre()?></h1>
</div>
<?php 
foreach ($evaluaciones as $evaluacion): 
?>
 <div class="subtitulo1">
  <h2><?php echo __('Evaluación') ?> <?php echo $evaluacion->getTitulo()?></h2>
 </div>
<div id="listado">
<table cellspacing="0">
<thead>
<tr>
  <th><?php echo __('Nombre') ?></th>
  <th><?php echo __('Faltas totales') ?></th>
  <th><?php echo __('Retrasos totales') ?></th>
  <th><?php echo __('Faltas justificadas') ?></th>
  <th><?php echo __('Faltas sin justificar') ?></th>
  <th><?php echo __('Retrasos justificados') ?></th>
  <th><?php echo __('Retrasos sin justificar') ?></th>
</tr>
</thead>
<?php 
$x=1;
foreach ($alumnos as $alumno):?>
<tbody>
<?php 
$total_faltas = 0;
$faltas_justif = 0;
$faltas_nojustif = 0;
foreach ($faltas as $falta): 
if ($falta->getAlumnoId() == $alumno->getId() && $falta->getEvaluacionId() == $evaluacion->getId())
{
  $total_faltas++;
}

if ($falta->getAlumnoId() == $alumno->getId() && $falta->getEvaluacionId() == $evaluacion->getId() && $falta->getJustificado() == true)
{
  $faltas_justif++;
}

if ($falta->getAlumnoId() == $alumno->getId() && $falta->getEvaluacionId() == $evaluacion->getId() && $falta->getJustificado() == false)
{
  $faltas_nojustif++;
}
endforeach; //faltas

$total_retrasos = 0;
$retrasos_justif = 0;
$retrasos_nojustif = 0;
foreach ($retrasos as $retraso): 
if ($retraso->getAlumnoId() == $alumno->getId() && $retraso->getEvaluacionId() == $evaluacion->getId())
{
  $total_retrasos++;
}

if ($retraso->getAlumnoId() == $alumno->getId() && $retraso->getEvaluacionId() == $evaluacion->getId() && $retraso->getJustificado() == true)
{
  $retrasos_justif++;
}

if ($retraso->getAlumnoId() == $alumno->getId() && $retraso->getEvaluacionId() == $evaluacion->getId() && $retraso->getJustificado() == false)
{
  $retrasos_nojustif++;
}
endforeach; //retrasos
if ($x%2 == 0)
{
  $fila = "p";
}
else
{
  $fila = "i";
}
  
?>
<tr class="<?php echo $fila ?>">
  <td><?php echo $alumno->getNombre() ?></td>
  <td><?php echo $total_faltas; ?></td>
  <td><?php echo $total_retrasos; ?></td>
  <td><?php echo $faltas_justif; ?></td>
  <td><?php echo $faltas_nojustif; ?></td>
  <td><?php echo $retrasos_justif; ?></td>
  <td><?php echo $retrasos_nojustif; ?></td>
</tr>
<?php
$x++;
endforeach; //alumnos 
?>
</tbody>
</table>
</div>
<div class="lineasep"></div>
<?php 
endforeach; //evaluaciones
?>
<div id="linea"></div>
<div class="exit">
<?php 
echo link_to(__('Volver'), 'falta/totalgrupolist?fecha='.$fecha); 
?>
</div>	
</div>



