<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Javascript') ?>
<?php use_helper('Date') ?> 
<?php use_helper('I18N') ?>

<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Faltas en la asignatura '); echo $asignatura->getNombre();?></h1>
<h2><?php echo "("; echo $evaluacion->getTitulo(); echo ")";?></h2>
</div>
<br />
<div id="listado">
<table cellspacing="0">
<thead> 
<tr>
  <th><?php echo __('Alumno') ?></th>
  <th><?php echo __('Faltas') ?></th>
  <th><?php echo __('Faltas justificadas') ?></th>
  <th><?php echo __('Falta sin justificar') ?></th>
  <th><?php echo __('Retrasos') ?></th>
  <th><?php echo __('Retrasos justificados') ?></th>
  <th><?php echo __('Retrasos sin justificar') ?></th>
</tr>
</thead>
<?php 
$x=1;
$fila = "i";
?> 
<tbody>
<?php   
foreach ($alumnos as $alumno):
?>
<tr class="<?php echo $fila ?>">
<td><?php echo $alumno->getNombre(); ?></td>
<?php 
  $total = 0;
  $sinjustif = 0;
  $justif = 0;
  foreach ($faltas as $falta):  
    if ($falta->getAlumnoId() == $alumno->getId())
    {
      $total++;
      if ($falta->getJustificado() == true)
      {
        $justif++;      
      } 
      else
      {
        $sinjustif++;      
      }   
    } 
  endforeach; //faltas 
 ?>  
<td><?php echo $total; ?></td>
<td><?php echo $justif; ?></td>
<td><?php echo $sinjustif; ?></td>
<?php 
  $total = 0;
  $sinjustif = 0;
  $justif = 0;
  foreach ($retrasos as $retraso):  
    if ($retraso->getAlumnoId() == $alumno->getId())
    {
      $total++;
      if ($retraso->getJustificado() == true)
      {
        $justif++;      
      } 
      else
      {
        $sinjustif++;      
      }   
    } 
  endforeach; //faltas 
 ?> 
<td><?php echo $total; ?></td>
<td><?php echo $justif; ?></td>
<td><?php echo $sinjustif; ?></td> 
<?php 
$x++; 
if ($x%2 == 0)
{
  $fila = "p";
}
else 
{
  $fila = "i";
} 
echo "</tr>"; 
endforeach; //alumnos 
?>
</tbody>
</table>

<div id="linea"></div>
<div class="exit">
<?php 
echo link_to(__('Volver'), 'falta/index?fecha='.$fecha); 
?>
</div>	
</div>
</div>
