<?php

/*
  This file is part of iTutor.
  Copyright (C) 2008 Oihane Garcia Bolumburu <oihaneg@gmail.com>
  Copyright (C) 2008 Ion Jaureguialzo Sarasola <widemos@gmail.com>

  iTutor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  iTutor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with iTutor. If not, see <http://www.gnu.org/licenses/>.
*/

?>
<?php
// auto-generated by sfPropelCrud
// date: 2007/12/04 09:35:39
?>
<?php use_helper('Date') ?>
<?php use_helper('I18N') ?>
<div id="contenedor">
<div id="titulo">
<h1><?php echo __('Visualizar prueba') ?></h1>
</div>
<div id="mostrar">

<table cellspacing="0">
<thead>
<tr>
  <th>&nbsp;</th>
  <th id="sf_admin_list_th_id"><?php echo __('Datos prueba') ?></th>
</tr>
</thead>
<tbody>
<tr>
<th><?php echo __('Id') ?>: </th>
<td class="i"><?php echo $prueba->getId() ?></td>
</tr>
<tr>
<th><?php echo __('Evaluación') ?>: </th>
<td class="p"><?php
      foreach ($evaluaciones as $evaluacion):
      if ($evaluacion->getId() == $prueba->getEvaluacionId())
      { 
          echo $evaluacion->getTitulo();
      }
      endforeach;
      ?>
      </td>
</tr>
<tr>
<th><?php echo __('Asignatura') ?>: </th>
<td class="i"><?php
      foreach ($asignaturas as $asignatura):
      if ($asignatura->getId() == $prueba->getAsignaturaId())
      { 
          echo $asignatura->getNombre();
      }
      endforeach;
      ?>
      </td>
</tr>
<tr>
<th><?php echo __('Dia') ?>: </th>
<td class="p"><?php 
      include_component ('principal','dias', array (
      'dia' => $prueba->getDia() 
      ));?></td>
</tr>
<tr>
<th><?php echo __('Hora') ?>: </th>
<td class="i"><?php 
      include_component ('principal','horas', array (
      'hora' => $prueba->getHora() 
      ));?></td>
</tr>
<tr>
<th><?php echo __('Fecha') ?>: </th>
<td class="p"><?php echo $prueba->getFecha() ?></td>
</tr>
<tr>
<th><?php echo __('Duración') ?>: </th>
<td class="i"><?php echo $prueba->getDuracion() ?> <?php echo __('horas')?></td>
</tr>
<tr>
<th><?php echo __('Porcentaje') ?>: </th>
<td class="p"><?php echo $prueba->getPorcentaje() ?> %</td>
</tr>
<tr>
<th><?php echo __('Observaciones') ?>: </th>
<td class="i"><?php echo $prueba->getObservaciones() ?></td>
</tr>
<tr>
<th><?php echo __('Actualizado') ?>: </th>
<td class="p"><?php echo $prueba->getUpdatedAt() ?></td>
</tr>
</tbody>
</table>

<div id="linea"></div>	
<div class="edit">
<?php echo link_to(__('Editar'), 'prueba/edit?id='.$prueba->getId().'&grupoid='.$grupoid.'&fecha='.strtotime($prueba->getFecha())) ?>
</div>
<div class="list">
<?php 
if ($grupoid != 0)
{
  echo link_to(__('Listado'), 'prueba/listado?grupo=0&dia='.$prueba->getDia().'&hora='.$prueba->getHora().'&asignatura='.$prueba->getAsignaturaId().'&grupoid='.$grupoid.'&fecha='.strtotime($prueba->getFecha()));
}
else
{
 echo link_to (__('Listado'), 'prueba/list?grupo=0&grupoid=0&fecha='.$fecha);
} ?>
</div>
<div class="edit">
<?php echo link_to(__('Introducir Notas'), 'prueba/alumnolist?prueba='.$prueba->getId().'&grupo=0&grupoid='.$grupoid.'&fecha='.strtotime($prueba->getFecha()));?>
</div>
</div>
</div>
