<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/01 21:17:38
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => 'principal/index',
  'app_sf_guard_plugin_success_signout_url' => 'principal/index',
));
