<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/01 21:17:38
sfConfig::add(array(
  'sf_i18n_default_culture' => 'es',
  'sf_i18n_source' => 'XLIFF',
  'sf_i18n_debug' => false,
  'sf_i18n_cache' => true,
  'sf_i18n_untranslated_prefix' => '[T]',
  'sf_i18n_untranslated_suffix' => '[/T]',
));
