<?php
// auto-generated by sfCacheConfigHandler
// date: 2016/09/08 08:50:29
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

