<?php
// auto-generated by sfCacheConfigHandler
// date: 2016/09/02 17:26:07
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

