<?php
// auto-generated by sfViewConfigHandler
// date: 2016/09/02 17:26:07
$context  = $this->getContext();
$response = $context->getResponse();


  $templateName = $response->getParameter($this->moduleName.'_'.$this->actionName.'_template', $this->actionName, 'symfony/action/view');
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!$context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Gestión de alumnos', false, false);
  $response->addMeta('robots', 'nofollow', false, false);
  $response->addMeta('description', 'Gestión de alumnos', false, false);
  $response->addMeta('keywords', 'symfony, project', false, false);
  $response->addMeta('language', 'es', false, false);

  $response->addStylesheet('estilos', '', array ());
  $response->addStylesheet('menu', '', array ());
  $response->addStylesheet('menu_secundario', '', array ());
  $response->addStylesheet('listado', '', array ());
  $response->addStylesheet('mostrar', '', array ());
  $response->addStylesheet('admin', '', array ());
  $response->addStylesheet('editar', '', array ());
  $response->addStylesheet('horario', '', array ());
  $response->addStylesheet('calendario', '', array ());


